eclipse-capella/capella

tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/headless/selector/TestSessionManagerListener.java

When the org.polarsys.capella.test.diagram.common.ju is present and
opened in dev environment, NPE are thrown on representation creation as:
- the HeadlessCapellaAnalysisSelector is installed by the
TestSessionManagerListener on every created sessions.
- excepted for some specific tests, the selectedUri is never set
Change-Id: I17a28ce1fd3383780aeb575d4ae7f7634b0c8688

[test] Avoid NPE thrown by test framework in runtime.

---

core/plugins/org.polarsys.capella.core.commandline.core/src/org/polarsys/capella/core/commandline/core/AbstractCommandLine.java

Change-Id: Iadacdf6baf2c5da7b9eb308c07fe149ffe383d89

[559825] fix NPE thrown when executing a commandline with"-forceoutputfoldercreation" argument but without "-outputfolder" argument

---

core/plugins/org.polarsys.capella.core.platform.sirius.adapter/src/org/polarsys/capella/core/platform/sirius/adapter/SiriusToCapellaAdapterFactory.java

Catch IllegalStateException(LifeCycleException). This exception might
occur if the distant resource has been closed in the meantime (CDO
context).
Change-Id: I04a82f7cc14a952aaca57d4d999bd79d638d7291

[561414] Avoid exceptions because of unreachable distant resources

---

core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java

This is a regression with the use of the common dialog instead of a
MessageDialog. OK button was not focused by default
Bug: 560934
Change-Id: Ie2164cf1624331b0dc343dd672fcf8192b186220

[560934] Set default buttons on deletion dialog

---

common/plugins/org.polarsys.capella.common.platform.sirius.customization/META-INF/MANIFEST.MF
common/plugins/org.polarsys.capella.common.platform.sirius.customization/src/org/polarsys/capella/common/platform/sirius/customisation/SiriusCustomizationPlugin.java
core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/META-INF/MANIFEST.MF
core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/PerspectivePlugin.java

All sirius preferences are located into sirius.customization plugin
Change-Id: I4f6a3be5805e8ff3a0648a7573a3d16f1becce09

[553820] Move preferences customization to sirius.customization

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ReuseOfComponentsModel/ReuseOfComponentsModel/.project
tests/plugins/org.polarsys.capella.test.model.ju/model/DiffMergeSourceV1Prj/.project
tests/plugins/org.polarsys.capella.test.table/model/SF-OA/.project
tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/.project

* Simplify and adapt capella.setup for the following:
- Use github repositories
- Addons are now downloaded for all Capella Developers
- Target platform calculation much simpler now, only repo
urls are needed
- Users of the current model should ditch their current installs
and reinstall with the new setup
* Some test projects had missing natures
- This is important, because capella nature is used
to identify test projects, which shouldn't be imported
into the workspace
Signed-off-by: Felix Dorner <felix.dorner@gmail.com>

[releng][oomph] Setup model rewritten

---

core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchConstants.java
core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettings.java

- Fixed AssertionFailedException when "Whole word" and "Regular
expression" options are used together
-- A message informing the user is displayed and the search is not
performed
- Fixed regex information in both text box and class filter
- Fixed search queries that use the String Matcher format
-- The String matcher is not as powerful as regex but allows the use of
\* for any string, \? for a character etc.
Change-Id: I2ebf69f58c97de9453f42bfe84dbde49dccbd586

Search behavior fixes

---

releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

R20130827064939 and R20140525021250 have been moved to
archive.eclipse.org
R20160221192158 contains all our required dependencies with same
versions. only jsoup hasn't the same qualifier but is used only in
junit.
Change-Id: I92febfe2845214db808a954a9a15eb6eb61b1a3f

[releng] Avoid use archived orbit repository

---

core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchConstants.java
core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractCapellaSearchForContainerArea.java
core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaLeftSearchForContainerArea.java

- Collapse the left panel class tree by default
- Add 'matching items will be hidden' note for the class filters
Change-Id: I8aa407e16b7b9a33db21412df8ccea7a0bbe42dd

Left panel class tree should be collapsed

---

core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/FileModificationPreCommitListener.java

This listener is added in the constructor of the class but was never
removed. This commit removes this listener during the dispose.
Bug: 563107
Change-Id: I7116d548e87f5dd222b503c63fbd3656314629db

[563107] Avoid a memory leak in FileModificationPreCommitListener

---

core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/helpers/SelectionDialogHelper.java

Bug: 563293
Change-Id: Id3c89a2bb48269fec3e6a816c8c6f249c051176a

[563293] SelectionDialogHelper.simplePropertiesSelectionDialogWizard doesn't allow multiple selection

---

core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

When two diagrams are opened and displaying description tab, if user
changes description of the first then switch to other diagram editor
while keeping focus on description, he may lost its description
Bug: 561365
Change-Id: I3139f3b9add7b981cb3d8fa5a5192c6bb973ac86

[561365] Richtext can lost the last modification when switching tab

---

core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/uml2/rules/Rule_InteractionOperand.java
tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.melodymodeller
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ScenarioUml2_01.java

Bug: 563327
Change-Id: I840fe8289432ec51bc54a953241bd48830b06c0f

[563327] In scenario initialization Guard are not referenced on operands

---

common/plugins/org.polarsys.capella.common.platform.sirius.ted/src/org/polarsys/capella/common/platform/sirius/ted/SiriusSessionFactory.java

This commit avoids to use the final parameter transactionalEditingDomain
that had the same name as the field transactionalEditingDomain of DASI.
This causes the creation, at compilation time, of a
val$transactionalEditingDomain in the DASI. This "new field" is not set
to null in DASI.close and can cause a memory leak.
Bug: 563340
Change-Id: I72d27ff022bbdc52534a7ff5b4fb95bf30665363

[563340] Clean code of SiriusSessionFactory.createSession

---

common/plugins/org.polarsys.capella.common.ui.toolkit.browser/META-INF/MANIFEST.MF
common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/category/CategoryImpl.java
common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/category/CategoryRegistry.java
common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/category/ICategory.java
common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/internal/TypeHelper.java
core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaInterpreter.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java

- Query evaluation should depend on object resolution (e.g. part/type in
mono-part mode)
- Query symbolic name is defined from SB code
Change-Id: Ie66aa419def26c9ee44ebd9bed41ca2af8e022be

- Fix duplicate queries problem

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/preferences/TitleBlockPreferenceField.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/preferences/TitleBlockPreferencesInitializer.java

- Insert line didn't work on empty cells
- Title Block with empty cells could not be inserted into diagrams
Bug: 558032
Change-Id: I69e5e4362d3fd648970a4f2c3406838d99e5b363

[558032] Fix insertions of Title Blocks

---

core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/fields/TitleBlockBasicElementGroup.java
core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/RepresentationAnnotationHelper.java
core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/TitleBlockItemProvider.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/TitleBlockItemProviderDecorator.java
tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/titleblocks/InsertRemoveTitleBlockTool.java

It avoids to add SRM resources to DAnalysis Semantic Resources when
DRepresentation are stored on SRM resources
Bug: 558032
Change-Id: I5b51ee6fb2a36ffd41c784c56f5731e1a6223e89

[558032] Store Title Block on DRepresentationDescriptor instead of DRepresentation

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup

The epl 2.0 changes break the xml in Capella setup. This reverts the corrupted file. Please merge this asap, otherwise Capella.setup will be removed from the catalog. We don't want that.

[564517] Fix broken xml in Capella.setup

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/preferences/TitleBlockPreferenceField.java

blocks in the preference page
Bug: 558032
Change-Id: I3d3bc514cc492485adeeb6b33d2ac9caceb6a946

[558032] Avoid exceptions when insert columns/rows of diagram title

---

releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

v1.3.x. branch isn't compiling because the sirius stable repo doesn't exist any more. use 6.1.4. release now.

[releng] Switch to Sirius 6.1.4 Release

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

There is no code change compared to 6.3.2 but only the bump to 6.4.0 and
the build done on 2020-06 platform
Change-Id: I98b50d35920b49d0d4a99bc135bc67f0bd653ed7

[releng] Update Sirius version to 6.4.0-S20200716-044517 based on 2020-06

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java

In order to compute the initial selection, the following aql expression
is used `aql:self.void2Null(self.getIntersection(visibleTargets,scope))`.
The `getIntersection` method takes two `java.util.List` as a parameter,
but for CEI|CII we provide a `java.util.Set` parameter.
Since the method signature does not match with the runtime arguments, we
get a void -> null initial selection.
Change-Id: I9d634561b0b22757128c9857486dc5e203395e40

[565894] [CEI|CII] Show/Hide Actors dialog does not show existing actors

---

core/plugins/org.polarsys.capella.core.data.menu.contributions/src/org/polarsys/capella/core/data/menu/contributions/epbs/EPBSArchitectureItemContribution.java
core/plugins/org.polarsys.capella.core.data.menu.contributions/src/org/polarsys/capella/core/data/menu/contributions/la/LogicalArchitectureItemContribution.java
core/plugins/org.polarsys.capella.core.data.menu.contributions/src/org/polarsys/capella/core/data/menu/contributions/pa/PhysicalArchitectureItemContribution.java
core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/ModelCreationHelper.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/BlockArchitectureExt.java
core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/actions/AllocationManagementData.java
core/plugins/org.polarsys.capella.core.re/src/org/polarsys/capella/core/re/rules/cs/PhysicalPortRule.java
core/plugins/org.polarsys.capella.core.re/src/org/polarsys/capella/core/re/rules/fa/ComponentPortRule.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ContextServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/showhide/ShowHideABComponent.java
core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/commands/DiagramTransitionRunnable.java
core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/handlers/ArchitectureHandler.java
core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/IntramodelTransitionCommand.java
core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/TransitionCommandHelper.java
core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/handlers/traceability/config/MergeSourceConfiguration.java
core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/handlers/traceability/config/MergeTargetConfiguration.java
core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/handlers/traceability/config/TransformationConfiguration.java
core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/common/StateMachineRule.java
core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/cs/ComponentRule.java

The problem resides in the use of the
`org.polarsys.capella.core.model.helpers.BlockArchitectureExt.getFirstComponent(BlockArchitecture,
boolean: TRUE)` method in functions called at the Operational Level.
Since there is no Operational System concept at that level, this method
constantly creates a new Entity at each call.
Change-Id: I3f031760613b3c6759910bce56ea1d479d7a9e85

[566264] Some operations might create unwanted Entities as a side effect

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/move/representation/MoveRepresentationMenuManager.java
core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/RepresentationActionProvider.java

This commit display the "Move Diagrams" menu after opening a diagram.
This fix keeps the cleaning of the MoveDiagrams submenu items. Existing
associated rcptt tests do not fail.
Bug: 566008
Change-Id: Iba6426e8cbfb243c6aaf85d78e799418bfef61ff
Signed-off-by: jmallet <jessy.mallet@obeo.fr>

[566008] Display "Move Diagrams" menu after opening a diagram.

---

core/plugins/org.polarsys.capella.core.data.cs.ui.quickfix/src/org/polarsys/capella/core/data/cs/ui/quickfix/generator/DWF_DC_36_Generator.java
core/plugins/org.polarsys.capella.core.data.cs.ui.quickfix/src/org/polarsys/capella/core/data/cs/ui/quickfix/resolver/DWF_DC_36_Children_To_Closest_Valid_Ancestor_Resolver.java
core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/OAB-DragAndDrop/.project
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/OAB-DragAndDrop/OAB-DragAndDrop.afm
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/OAB-DragAndDrop/OAB-DragAndDrop.aird
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/OAB-DragAndDrop/OAB-DragAndDrop.melodymodeller
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropOABActors.java

- Forbid actor decomposition
- Add a quick fix on DWF_DC_36 that moves the children to the nearest
valid ancestor
- Add JUnit
Change-Id: Iac2be81afff2e9c133ec7f098b39666ba95df33c

[566380] Actors can be decomposed in OAB diagrams by DnD model elements

---

core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchPage.java
core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractCapellaSearchForContainerArea.java
core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaLeftSearchForContainerArea.java

There are some problems with the layout of Capella search page:
1. The filtered tree does not grab the extra space when possible. When we resize the Search dialog or expand it, the filtered tree does not change its size.
2. The filter checkboxs are not well layouted. Sometimes it's overlapped by other fields.
Bug: 566393
Change-Id: I1d7784618f3cea70fc4b7ccb409c3a8065faf260

[566393] Problems with the layout of the Capella search page

---

core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

Due to the asynchronization of Nebula Richtext editor events, when we switch quickly between elements with an opened description editor in property view, the description of an element can be unexpectedly replaced by the description of another element. 
The solution for the bug 561365 was to dispatch all the events of Nebula Richtext editor for each action. However, this has some side-effects, for example double-click events appear without any reason.
We need to find a way to react to asynchronized events of Nebula Richtext editor instead of forcing them to be synchronized with our UI events.
Bug: 561365
Change-Id: Ie4febe641226dd431502e9974b3b00b8459f8498

[566392] Description can be lost when switching quickly between elements with an opened description editor in property view

---

core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/DescriptionPropertySection.java
doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.html
doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.mediawiki

* The bug is due the fact that editor's href path MUST be set before the editor is ready. Since we load the data for the editor in asynchronous jobs (to avoid concurrency problems), we must find a way to set the href path before launching the editor.
* Update the doc about known issues
Bug: 566558
Change-Id: I2ad8e11afb55a6dc6c9ac69b1831da6a727321dc

[566558] Inserting an image in relative path fails on Properties description tab

---

releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

* Integrate new Kitalpha to include the fix
Bug: 566627
Change-Id: I9dc6ac6425b4a2d7157070144574087cae5342ed

[566627] Refreshed editor does not have listeners installed

---

releng/plugins/org.polarsys.capella.rcp.product/pom.xml

We want to remove maven folder in plugins in the final product but these
plugins are already signed. If the content of the plugin changes, we'll
end up with invalid plugins in our product.
Change-Id: I33137e98f5b2defae614a245c9d29118e98be03c

[Releng] Do not remove maven folders in the final product

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaSaveable.java

This can happen in team context when then connection with the server is
lost.
Bug: 566436
Change-Id: I5aff5850fcea7b5648dc4d8d73de8aa395d88e6e

[566436] Do not consider Capella session as dirty if it is closed

---

core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/commands/ESToISCommand.java
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_01.java
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_02.java

- bug fix: if OAS was already transited, and we transit an OES after
(this OES has an invalid reference to the already transited OAS), then
an invalid reference to OAS is set.
Change-Id: Ibcb53f5ae11cc9f02ef6e5680689d8558d1276c7

[567469] Transition reference invalid

---

core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/sections/DiagramRepresentationPropertySection.java

Change-Id: I0742b77608371977c961a705064b46a45c93efb5

[cleanup] Avoid NPEs in diagram property sections when diagrams or descriptors are no more available

---

core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java

This avoids potential "Invalid thread access".
Bug: 566434
Change-Id: I842eabddab9d3cae38ef7a5f43abbf020c351541

[566434] Always call SemanticBrowserView.setInput in UI Thread

---

core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/actions/MetricAction.java
core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/core/MetricTree.java
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/build.properties
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/src/org/polarsys/capella/test/progressmonitoring/ju/testcases/MetricTest.java
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/epbsMetric.txt
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/laMetric.txt
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/oaMetric.txt
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/paMetric.txt
tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/saMetric.txt

The resulting CSV file after export to Excel of metrics on model is not sorted due to a refactoring done with the commit I093788bb00785f899098c7f2710ba0b1eeae56a4.
- Also take into account the case when meta-classes have the same name: use the fully qualified name to have the exact order when displaying in tree and exporting to csv.

[568599] [Regression] The resulting CSV file after export to Excel of metrics on model is not sorted

---

core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/TypedElementHasDifferentNameThanTypeResolver.java
core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/core/validation/capellaelement/TypedElementHasDifferentNameThanType.java
core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/information/services/ExchangeItemExt.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForExchangeItemAndExchangeItemInstance.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelEditingDomainListener.java
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.html
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.mediawiki
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/.project
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.afm
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.aird
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.capella
tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/IRulesTestSuite.java
tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_45.java

Abstract Type
Abstract Type Elements should have the same name as their Abstract Type
in the following cases:
- **Part**: In singleton component mode
- **Exchange Item Instance**:  If the Exchange Item has a single Exchange Item Instance
Work done:
- Add name synchronization between Exchange Item and Exchange Item
Instance
- Add validation rule
- Add quick fix
- Add JUnit
- Update embedded documentation
Change-Id: I427313bf5c67be4af9c64f77e0b5361a49892dac

[568858] Enforce same name between Abstract Type Elements and their

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

https://download.eclipse.org/sirius/updates/stable/6.4.0-S20201119-043506/2020-06/
Change-Id: Id11a2818f608522b48652cec63c5831ee7371efb

[releng] Update Sirius version to 6.4.0-S20201119-043506

---

core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ModelElementConstraints.java

referencing elements inside the Semantic Browser view

#2024 Constraints on OEntities and OActors should be displayed in

---

core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/StateMachineExt.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDMixedStatesModes.java
tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDTestSuite.java

Fixes #2034 
Change-Id: I05f9d72e26af0406d34f1f1b0d2392497b9306d9

#2034 D&D and Copy-Paste disable Mix of Mode and State in Hierarchy

---

core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/plugin.xml
core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/src/org/polarsys/capella/core/data/common/ui/quickfix/resolver/DWF_SM_06ChildrenResolver.java
core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/src/org/polarsys/capella/core/data/common/ui/quickfix/resolver/DWF_SM_06Resolver.java
core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/src/org/polarsys/capella/core/data/common/ui/quickfix/resolver/DWF_SM_06SiblingResolver.java

Fixes #2057
Change-Id: Ib105ef9cbe8a15e92ed3ce5278f8f8abd848414d

#2057 Re-add siblings resolver + refactor

---

core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/DAnnotationChangeTrigger.java
core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/DAnnotationPrecommitListener.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/DAnnotationChangeTest.java

A ModelChangeTrigger has been added in order to react on notification
concerning DAnnotation and refresh its parent representation.
Change-Id: I0c574d1446f04e0841feee8d5b3fd401a52f55f6
Signed-off-by: Steve Monnier <steve.monnier@obeo.fr>

#2109 Notification on DAnnotation should refresh its representation

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

https://download.eclipse.org/sirius/updates/stable/6.5.0-S20210326-125830/2020-06/

[releng] Update Sirius version to 6.5.0-S20210326-125830

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/ScenarioCache.java

On some specific use cases with only Frames (4) and Operands (37), a 43%
reduction of the refresh has been observed.
Change-Id: I752b227a8d93ceca6d7f0e2e76575ec3e78ee15b
Signed-off-by: Nathalie Lepine <nathalie.lepine@obeo.fr>

#2106 Use ScenarioCache in Operand and Fragment computation

---

core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml

I added the missing `objectClass="org.eclipse.core.resources.IProject"` in `org.polarsys.capella.core.sirius.analysis/plugin.xml` to delete the Diagram tab.
Change-Id: I2537a502723decfd4d23e5818cc3deb68201d694
Signed-off-by: Glenn Plouhinec <glenn.plouhinec@obeo.fr>

#2160 Remove Diagram tab from aird properties page

---

core/plugins/org.polarsys.capella.core.semantic.queries/META-INF/MANIFEST.MF

…c.queries.
- org.polarsys.capella.core.semantic.queries.sirius.annotation
- org.polarsys.capella.core.semantic.queries.sirius.annotation.eoi
- org.polarsys.capella.core.semantic.queries.sirius.diagram
Change-Id: I752b347a8d93ceca6d7f0e2e76575ec3e78ee14c
Signed-off-by: Yvan Lussaud <yvan.lussaud@obeo.fr>

#2163 Export Representation queries from org.polarsys.capella.core.semantic.queries

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

https://download.eclipse.org/sirius/updates/stable/6.5.0-S20210416-090225/2020-06/

[releng] Update Sirius version to 6.5.0-S20210419-114904

---

core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/CapellaProjectHelper.java
core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/RepresentationHelper.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ComponentArchitectureBlankRefreshExtension.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/META-INF/MANIFEST.MF
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/.project
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.afm
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.aird
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.capella
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.melodyconnector
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/DiagramTargetUpdateDuringRefreshTest.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/TestHelper.java

mode are stored under the Part instead of its Component type
Change-Id: I02579f164dc6a904d6d3cb78787aa99aba1fb80f

#2178 XAB diagrams created from graphical model elements in mono-part

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

https://download.eclipse.org/sirius/updates/stable/6.5.0-S20210430-052046/2020-06/
Change-Id: I50da472603ca168cda4566373e5ae235a78123f0

[releng] Update Sirius version to 6.5.0-S20210430-052046

---

releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

https://download.eclipse.org/sirius/updates/milestones/6.5.0rc2/2020-06/
Just 2 changes since the last Sirius version:
* one to fix a problem, for bugzilla 571115, detected during validation
phase,
* one to avoid a random failure on Collab automatic tests.
Change-Id: I81d3104594c34a39e32dd3c9dfddfbbb76443fd5

[releng] Update Sirius version to 6.5.0 RC2 (respin of Sirius IT3)

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/plugin.xml

The "Modeling Project" action is now hidden from the Capella perspective.
Change-Id: I0f116bb49f53b98d47a920a2ec3c37b4e94544b8
Signed-off-by: Glenn Plouhinec <glenn.plouhinec@obeo.fr>

#2208 Hide "Modeling Project" from Capella perspective exclusively

---

common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/handlers/traceability/LevelBasedTraceabilityHandler.java
core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/handlers/traceability/ReconciliationTraceabilityHandler.java
tests/plugins/org.polarsys.capella.test.transition.ju/META-INF/MANIFEST.MF
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/DataPkgReconciliation.java
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionTestSuite.java

Fixes #2214
Change-Id: I5c796d2d23913d9b799c36ee040c4a343df4ec08

#2214 [Transition] DataPkgs and their children are mapped in the reconciliation traceability handler even though they are not predefined elements

---

core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/provider/LibrarySAXXMIHandler.java

Importing a shared Capella project where the root element (Project) has
a status leads to an UnresolvedReferenceException that can be ignored in
LibrarySAXXMIHandler.handleForwardReferences
Bug:2241
Change-Id: I5295d0fed0b247acf38aa2d5fcc3e6c29cb70d3d
Signed-off-by: Steve Monnier <steve.monnier@obeo.fr>

#2241 Ignore non-LibrariesPackage related UnresolvedReferenceException

---

common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/handlers/traceability/config/ExtendedTraceabilityConfiguration.java

If multiple vp extend TraceabilityConfiguration, it is not clear which
handler is used.
Change-Id: I0c379c044601c142824c504c1ca1b3bc3ee1a1dd

#2261 Handle selection of transformation handlers

---

core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/META-INF/MANIFEST.MF
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.properties
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.xml
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ImagePathInDiagramCheck.java
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ImagePathOnRichTextAttributeCheck.java
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ImagePathResolver.java
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.html
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.mediawiki
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

Two new validation rules are added:
* I_46 - Check that the image used for diagram nodes is found
* I_47 - Check that images used in rich text is found (Capella and
diagram descriptions etc)
The corresponding quick fix is also added.

#2269 Add validation rules for wrong image path

---

core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java

Using a cache to store the result of queries to find representations
that use a particular element allows to divide the refresh time of the
Semantic Browser by 2 by avoiding to look for references several times.
Change-Id: Id884ebd43bc5c71123474152c9566feeab04ccbf
Signed-off-by: Glenn Plouhinec <glenn.plouhinec@obeo.fr>

#2290 Cache the result of queries to improve Semantic Browser perfs

---

common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/view/ISemanticBrowserViewPart.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/SemanticBrowserRefreshTest.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/UnsynchronizedSemanticBrowser.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java

Since Sirius bugzilla 578436 [1], the selection behavior has been
improved to avoid 2 refreshes of the listening views.
In this commit, the Semantic Browser view is adapted to these changes.
The refresh condition now also considers the "original selection", ie
EditPart, on not only the corresponding semantic element.
[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=578436

#2323 Adapt Semantic Browser view to the new Sirius selection behavior

---

core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalPath_PhysicalComponents.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalPath_PhysicalLinks.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/PhysicalPathInvolvedComponents.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/PhysicalPathInvolvedPhysicalLinks.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java

Add new query summing up the involved components for a PhysicalPath
element. Involved components are resolved through involved links and
ports.
Added test case for this query.
Added a test case for the PhysicalPath to InvolvedPhysicalLinks (and the
item query to PhysicalComponents).

 #2374 Add PhysicalPath Involved Components Query

---

core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.properties
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.xml
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ImagePathMassResolver.java
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/Messages.java
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/messages.properties
doc/plugins/org.polarsys.capella.ui.doc/.settings/org.eclipse.core.resources.prefs
doc/plugins/org.polarsys.capella.ui.doc/html/02. Workbench Basics/2.3. Managing images.html
doc/plugins/org.polarsys.capella.ui.doc/html/02. Workbench Basics/2.3. Managing images.mediawiki
doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/3.7. How to rename a Capella Project.html
doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/3.7. How to rename a Capella Project.mediawiki
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.html
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.mediawiki
releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

It also updates the doc.
Bug: https://github.com/eclipse/capella/issues/2413

#2413 Add a quick fix to replace all image paths

---

core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/ctx/services/CapabilityExt.java
core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/abstractCapability/MDCHK_Capability_FunctionalChains_Involvement.java
core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/AbstractCapability_ExternalReferencedFunctionalChains.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/AbstractCapability_ExternalReferencedScenarios.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/FunctionalChain_ExternalReferencedFunctionalChains.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/OperationalCapability_ExternalReferencedOperationalProcesses.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/OperationalProcess_ExternalReferencedOperationalProcesses.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/AbstractSemanticQueryTestCase.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/Capability_ExternalReferencedFunctionalChains.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/Capability_ExternalReferencedScenarios.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/FunctionalChain_ExternalReferencedFunctionalChains.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalCapability_ExternalReferencedOperationalProcesses.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalProcess_ExternalReferencedOperationalProcesses.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
tests/plugins/org.polarsys.capella.test.validation.rules.ju/META-INF/MANIFEST.MF
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_ca/Rule_DWF_CA_09.java

Added Semantic queries to display :
-External Referenced Functional Chains on AbstractCapability (except Operational Capability)
-External Referenced Functional Chains on Functional Chains (except Operational Processes)
-External Referenced Scenarios on AbstractCapability
-External Referenced Operational Processes on OperationalCapability
-External Referenced Operational Processes on Operational Process
Updated DWF_CA_09 Rule so that it checks that, for a given Capability , its External Referenced FunctionalChains are properly involved
Change-Id: I7dff5240b6f7668450898fbf31b3bffc15fef568

#2453 Added semantic queries on External Referenced Elements

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/OpenRelatedDiagramAction.java
core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/ui/sirius/DoubleClickBehaviourUtil.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/policies/OpenRelatedDiagramEditPolicy.java

If the referenced object had existing representations, double click worked
But if it hadn't, nothing would happen
Fixed it
Change-Id: Ibd862c938a2802eef6a4d225ab1fa6fa0fd16b37

#2449 Fixed double click on FC/PP/OP References

---

core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/fa/FunctionInputPortRule.java
core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/fa/FunctionOutputPortRule.java

During S-SS transition, exchange items allocated to functionInputPort were not properly transitionned in horizontal
Fixed it and potential issue on FunctionOutputPort
Change-Id: Ia96881cd0a6b0b601fc3ca87f872ef503d7b6d76

[#2487] Allocated ExchangeItems properly transitionned

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/titleblocks/InsertColumnInTitleBlockTool.java
tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/titleblocks/InsertLineInTitleBlockTool.java

In unsynchronized mode lines and columns were always inserted graphically at the end
Fixed it and updated junit tests
Change-Id: Ic3c26ae29a1fc593446b5a05e5b7600c3115c1e0

#2504 Fixed Insertion of TitleBlock lines and columns

---

tests/plugins/org.polarsys.capella.test.massactions.ju/META-INF/MANIFEST.MF
tests/plugins/org.polarsys.capella.test.massactions.ju/src/org/polarsys/capella/test/massactions/ju/testcases/view/shared/CollectionsInitializationTest.java
tests/plugins/org.polarsys.capella.test.massactions.ju/src/org/polarsys/capella/test/massactions/ju/testsuites/view/MAViewsTestSuite.java
tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/ShowInPropertiesDialogTest.java

Test that displaying a diagram with a SVG prior to opening a Mass view results in a crash of the latter.
Since there was no way to catch the exception or to get it from error log,
we directly call the code in error (which is from
org.Eclipse.collection)
Change-Id: Iba4d66a216cbcfb1679ce8ab960a5443f6a04f86

#2509 Test SVG regression

---

core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
core/plugins/org.polarsys.capella.core.data.interaction.validation/plugin.xml
core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/sequenceMessage/SequenceMessageInvokedOperationExchangeItems.java
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/completeness/ValidationRules.html
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/completeness/ValidationRules.mediawiki
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.mediawiki
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/transition/consistency/dataflows/ValidationRules.html
doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/transition/consistency/dataflows/ValidationRules.mediawiki
tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dcom/DCOMRulesTestSuite.java
tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dcom/Rule_DCOM_24.java

Fix checking rule to only raise an error if the SequenceMessage allocated exchange items are empty while the invoked Exchange has ExchangeItems.
Move rule from DWF_DS_25 to DCOM_24
Adapt warning message
Update documentation
Update tests

 #2498 Migrate DWF_DS_25 to DCOM_24

---

common/plugins/org.polarsys.capella.common.libraries/src/org/polarsys/capella/common/libraries/ILibraryManager.java
common/plugins/org.polarsys.capella.common.libraries/src/org/polarsys/capella/common/libraries/manager/LibraryManager.java
common/plugins/org.polarsys.capella.common.libraries/src/org/polarsys/capella/common/libraries/provider/ILibraryProvider.java
core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/propertyTester/CapellaModelIsLocalPropertyTester.java
core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/provider/AbstractCapellaProvider.java
core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/provider/CapellaWorkspaceProvider.java
doc/plugins/org.polarsys.capella.developer.doc/.settings/org.eclipse.core.resources.prefs
doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.2. Basic Use Case.html
doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.2. Basic Use Case.mediawiki

To bypass the limitation of library management for shared capella project (add/remove reference to shared library project), a property tester requires to be updated and an API added:
- CapellaModelIsLocalPropertyTester now uses the airdFile to check that the session is opened and contains a Capella model
- ILibraryManager and ILibraryProvider methods getAvailableModels has been doubled to give the session has a parameter. This allows CDOLibraryProvider to use the session to check for other models on the CDO repository it is connected to.
Change-Id: If79cedfe0128cc960f3da679706c5be85557c1e2
Signed-off-by: Steve Monnier <steve.monnier@obeo.fr>

#2514 Update library property tester and provider/manager APis

---

core/plugins/org.polarsys.capella.core.commandline.core/src/org/polarsys/capella/core/commandline/core/CommandLineArgumentHelper.java
doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki

Set getters that return deprecated variables to deprecated
Change-Id: Ie2fa344bd66ea7d2a44fa74d4a976d39c152c281

#2532 Fix CommandLineArgumentHelper Deprecation

---

common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/dialogs/AbstractExportDialog.java
core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/MetricMessages.java
core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/dialog/MetricDialog.java
core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/dialog/ProgressMonitoringOverviewDialog.java
core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/messages.properties

Default name are respectively set to "metrics" (default to metrics.csv) and "progress_monitoring" (default as progress_monitoring.csv)
Change-Id: Ia8ee207957db28de73ba352d22de43227270fffc

#2527 Add default filename for metrics & progressmonitor export

---

common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/dialogs/AbstractExportDialog.java
core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/export/prefs/ExportValidationPreferencePage.java

If extension was missing from filename, the export would always fail Now ensures that the filename ends with the file extension, or add it if missing
Change-Id: I47197c67a1039b28b6b0fd94e9550eac69320c13

#2526 Export Dialog / Export validation preference filename fix

---

core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/showhide/ShowHideFunction.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/testRefreshContextualElements/.project
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/testRefreshContextualElements/testRefreshContextualElements.afm
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/testRefreshContextualElements/testRefreshContextualElements.aird
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/testRefreshContextualElements/testRefreshContextualElements.capella
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/RefreshFCContextualElementsTest.java
tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java

When a diagram has, as a contextual element, a FC that involves internal functions not displayed,
on refresh the diagram was set dirty even though there were no changes
Ensure that we call the mapping candidate expression , on ShowHide.mustShow, to ensure that the node to show is displayable
Change-Id: I8cbb24b1350330228113084ee2873eb653e39787

#2548 Fixed Systematic dirty diagram on refresh

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/CopyUniqueIdentifierHandler.java

On xAB, we want also to copy the ID of the component or the part according to the multipart status. (use the CapellaAdapterHelper)

#2559 Fix Copy as Unique Identifier on diagram elements

---

core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.aird
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.capella
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DeleteSequenceLink.java
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/XABDiagramsProject.java

SequenceLink and Controlnode can now be deleted from diagram
Change-Id: I8bce39b4ff90d1f3d49b022503b7682e5eff17ba

#2576 Allow deletion of Sequence info on xAB diagrams

---

common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/menu/RecDynamicMenu.java
common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/menu/RplDynamicMenu.java
doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.2. Basic Use Case.html
doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.2. Basic Use Case.mediawiki
doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.6. Advanced Features.html
doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.6. Advanced Features.mediawiki
doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/5_Layout management/5_Layout management.html
doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/5_Layout management/5_Layout management.mediawiki
doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.html
doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.mediawiki
tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/common/SelectToolsTest.java

Fixed issue where select rec/rpl menu and actions wouldn't appear on edges, but would on their edge label
Change-Id: I380f5728040f79e7b65fc37c23ddf196b9373181

#2563 Select REC/RPL elements now works on edges

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/plugin.xml
core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/OpenAction.java
core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenRepresentationsAction.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/handlers/NavigationSemanticBrowserDoubleClickHandler.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/view/SiriusSemanticBrowserView.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser/META-INF/MANIFEST.MF
core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/handler/AbstractSemanticBrowserDoubleClickHandler.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/handler/DefaultSemanticBrowserDoubleClickHandler.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
tests/plugins/org.polarsys.capella.test.semantic.ui.ju/META-INF/MANIFEST.MF
tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testcases/SemanticBrowserCurrentElementNavigationTest.java
tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testsuites/SemanticUITestSuite.java

browser
Fixed issue where double-clicking wouldn't open properties wizard anymore
Fixed multi-selection in both project explorer and SB When pressing enter, the corresponding action is ran for each selected elements
actions being :
open diagram on representation descriptor
navigate on chain (FC/PP/OP) (create if 0, open if 1, ask if more than 1 diagram)
Updated condtions of ModelElementActionProvider so that it can also take representations descriptors
Change-Id: I4a2052c23ac73d218aa911a78842de99826e6d2f

#2596 Properties wizard can now be opened on double click in semantic

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/OpenAction.java

Fixed regression where diagrams could not be opened on double-click anymore
Change-Id: I8e7d1eb3897f2f3a9ecf2b523837790d53a1695f

#2596 Fixed regression on diagram opening

---

tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/PhysicalLinkIconAndLabel.java

Fixed issue with PhysicalLinkIconAndLabel unit test that used DNodeSpec instead of DNode
Change-Id: I817301f804212614f0ae4ecdb5f66aa23b7389af

#2605 Fixed test that does not work in Team context

---

core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/RepresentationHelper.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/SaxParserHelper.java
core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/WriteCapellaElementDescriptionSAXParser.java
core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/InvalidNameHandler.java
core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/navigation/CapellaNavigationModelElement.java

Fixed issue where, in team, if diagram hadn't been opened, link towards this diagram would be considered invalid
The DRepresentationDescriptor UID is now also used to resolve the diagram link
Change-Id: I05caddc0e0b52aaf05cbf5a2ff445fe2dee30c9d

#2624 Fixed Invalid hyperlink detection on referenced diagrams

---

core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/danalysis/CapellaAnalysisSelector.java

We use the shell provided in parameter instead of retrieving the shell from the getActiveShell() method.
A similar issue has been fix in Sirius in
SmartDialogAnalysisSelector#selectSmartlyAnalysis. On Linux, Display#getActiveShell might return null.
Bug: https://github.com/eclipse/capella/issues/2656

#2656: Fix NPE on Linux with the CapellaAnalysisSelector

---

common/plugins/org.polarsys.capella.common.tools.report.appenders.usage/src/org/polarsys/capella/common/tools/report/appenders/usage/util/UsageAppender.java

Bug: https://github.com/eclipse/capella/issues/2691

#2691 Fix Usage.log path and name in Linux/macOS

---

core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalLinkSource.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalLinkTarget.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalPortOwner.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/PhysicalLinkSourceTest.java
tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/PhysicalLinkTargetTest.java

add port and owner of the port of a physical link in referenced and referencing elements within semantic browser.
add junit

[Semantic Browser] physical links the corresponding connected ports are not displayed within the semantic browser

---

core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaNavigatorContentProvider.java

Whenever an additional resource is added to a Capella session (e.g. additional resources added by a Capella add-on), The Capella model explorer wants to add this resource's contents in the model tree.
The previous implementation unintentionally added the ContentsEList of the resource as a child, instead of the elements of this ContentsEList.
That caused the Capella model explorer to display a Node with a default image and a poor label obtained from ContentsEList.toString().

eclipse#2598 Fix resource display in model tree

---

releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform

It contains dependency to repackaged batik that prevent loading too much bundle (remove "Eclipse-BuddyPolicy: dependent" usage)

[releng] Update TP to gmf-runtime milestone S202401081627

---

core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java

#2717  On linux and macos, memento of Semantic Browser may not have all properties.
This leads the view to crash.

#2717 Fix NPE in Semantic Browser.

---

core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java

If the tracked element is owned by a closed session, do no save it
Change-Id: I0000000000000000000000000000000000000000

#2822 Fix for Richtext description

---

core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PhysicalComponentPhysicalLinks.java

query was abstract
Change-Id: I3df241dbe68edad51287079750bf452b63b3a746

#2700 Fix issue where semantic query couldn't be instantiated

---

core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/FunctionalChainExt.java
core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/DynamicOpenRepresentationContributionItem.java
core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/ui/sirius/DoubleClickBehaviourUtil.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/FunctionalChainInvolvementFunctions.java
core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/Scenario_RelatedFunctions.java
core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/policies/OpenRelatedDiagramEditPolicy.java
core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/wizards/CapellaWizardDialog.java
core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/wizards/EditCapellaCustomPropertyWizardPage.java
core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/handlers/NavigationSemanticBrowserDoubleClickHandler.java
tests/plugins/org.polarsys.capella.test.platform.ju/build.properties
tests/plugins/org.polarsys.capella.test.platform.ju/model/TestNavigationDoubleClick/.project
tests/plugins/org.polarsys.capella.test.platform.ju/model/TestNavigationDoubleClick/.settings/org.eclipse.core.resources.prefs
tests/plugins/org.polarsys.capella.test.platform.ju/model/TestNavigationDoubleClick/TestNavigationDoubleClick.afm
tests/plugins/org.polarsys.capella.test.platform.ju/model/TestNavigationDoubleClick/TestNavigationDoubleClick.aird
tests/plugins/org.polarsys.capella.test.platform.ju/model/TestNavigationDoubleClick/TestNavigationDoubleClick.capella
tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/CapellaNavigateOnDoubleClickTestCase.java
tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testsuites/PlatformTestSuite.java

Fix issue where all available diagrams would be available in open diagram menu
double click now automatically opens wizard properties when target is null on FC/PP/Sc references
Fixed SWT  Leak in Capella wizard dialog
Change-Id: I7253303250f4506399932bdd903d8d95cebf0715

#2829 Add robustness when target of FC/PP/Scenario reference is null

---

core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign

These preconditions are now evaluated with Sirius 7.4.0 they are duplicated and invalid anyway
Change-Id: I75ab45634ec224cc468575d419c743076969b780

#2854 Remove invalid preconditions on table creation tools

---

core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/MoveRepresentationsAction.java
tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ScenarioUml2_01.java

Reopened for https://github.com/eclipse-capella/capella/pull/2850 (wrong branch name containing parenthesis, causing sonar command not to be evaluated)

#2849 Fix Optional.orElseGet(null) leading to systematic error

---

tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout

An infrastructure change (see [1] and [2] has impacted the graphical results of the SysmodelMigrationLayout test. This requires changing the expected results. This file was directly retrieved from the continuous integration server [3].
[1] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5382
[2] https://www.eclipse.org/lists/cross-project-issues-dev/msg19990.html
[3] https://ci.eclipse.org/capella/view/Capella/job/capella-product/job/master/lastSuccessfulBuild/artifact/migration.sysmodel.aird.linux.layout

[test] Replace SysmodelMigrationLayout expected tests result

---

core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/AssociationCDBMigrationContributor.java

Following changes done in https://github.com/eclipse-capella/capella/issues/2913 the migration on specific samples showed some issue that this PR fixes:
- Fix an NPE that failed the migration if an edge add an empty bendpoint list (edge not displayed on the diagram).
- Fix the process that invert source and target of edges that failed for edges with the same source and target.
Change-Id: I7df8d6d319613f5da6151948efca460a2ab2989b

#2913 Fix NPE and edge source/target inversion

---

Jenkinsfile

Apply Jenkins/CI best practices and avoid builds hanging for days.

Add timeout and disable concurrent builds
