eclipse-capella/capella

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I5757f0709d1136021d89663e3f6e618382b01c71
> [releng] Integrate Kitalpha 1.4.0.202001100637

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/internal/navigate/NavigationAdvisor.java
Bug: 559237
Change-Id: I512c52f896e3108270ae0e1e439aa034cd0cfd97
> [559237] Fix Part presence issue for navigable elements

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
Bug: 559156
Change-Id: I9ee4ee391fc00307daa338ab9af9c2d861b885e2
Signed-off-by: yugansan <yugansan.yogaratnam@gmail.com>
> [559156] : Exception raised CapellaServices::getDiagramContainer for certain Graphical Elements

- tests/plugins/org.polarsys.capella.test.diagram.layout.ju/src/org/polarsys/capella/test/diagram/layout/ju/MigrationContribution.java
- tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout
Change-Id: I2142086f8c7dc14259742e4537c0630e69e30c7c
> [Test] Fix migration contribution of layout model

- core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/PropertyAssociation.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/PropertyAssociation.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
Bug: 559237
Change-Id: I82d165ce6c5cc38fde7132a5986069eaa59760d7
> [559237] Fix missing queries on Show Related Elements

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
Bug: 559156
Change-Id: I03ffae58f2b8890ae018d1863bb3503c5953c000
> [559156] Add javadoc for CapellaServices::getDiagramContainer

- Jenkinsfile
- releng/plugins/org.polarsys.capella.rcp.product/capella.product
- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
- Rename the launcher name to capella
- Remove eclipse folder from the product path
Change-Id: Ie1ea30c52f6e74f78f602d1cb58080cc01147309
> [releng] Reorganize the internal structure of the product

- core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/MigrationJobScheduler.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/BackupResourceContribution.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/Messages.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/messages.properties
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/handlers/ProjectMigrationHandler.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testcases/basic/MigrationEnabledTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
Bug: 559416
Change-Id: I5c32a5f63f9744984bf79b4b63687bd1f05d673b
> [559416] Robustify and improve user feedback for Capella project migration

- core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/MigrationJobScheduler.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/BackupResourceContribution.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/Messages.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/messages.properties
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/handlers/ProjectMigrationHandler.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testcases/basic/MigrationEnabledTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
migration (#25)
Bug: 559416
Change-Id: Iae6b5bec756ca5d14f6ea03cb0901367b2ba19be
> [559416] Robustify and improve user feedback for Capella project

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
Change-Id: I3eb2d4782ce67f9f1ed590040f27d2233d9f98c0
> [releng] Update Sirius version to 6.3.1-S20200114-10254

- Jenkinsfile
- Use github.isPullRequest() instead of faulty changeRequest()
- Run tests only for pull requests
Change-Id: I123f7f8fd3edec9e026bd4e4e05e78a714958dd8
> [releng] Update Jekinsfile

- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/activities/InitializeTransformationActivity.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Library/.project
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Library/Library.afm
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Library/Library.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Library/Library.melodymodeller
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/sa/FunctionalTransitionInLib.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionTestSuite.java
Bug 555485
Change-Id: I2039e475eeb5a2e448652dfcb9c937db5fef643d
Signed-off-by: Ali AKAR <ali.akar82@gmail.com>
> [555485] Transition from OA to SA using libraries

- Jenkinsfile
- Rewrite Jenkinsfile to make use of the capella-pipeline-library
https://github.com/eclipse/capella-pipeline-library
Change-Id: I60ad0b967a43e1057090ff860c63312cd590c51f
> [releng] Rewrite Jenkinsfile

- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
- doc/plugins/org.polarsys.capella.ui.doc/toc.xml
Change-Id: I173ebaa60093c05ab253a310c3e940d70a7b3799
> [Doc] Add the section about multi-user installation

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/EPBS.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ia9d9f42d35f0920845230e31b86679f763e4c22d
> [releng] Update Kitalpha to 1.3.2RC1

- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/AbstractCapellaNewDiagramHyperlinkAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/AbstractNewScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/ModelCreationHelper.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/la/AbstractNewLAScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/la/NewExchangeScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/la/NewFunctionalScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/la/NewScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/oa/AbstractNewOAScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/oa/NewActivityScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/oa/NewInteractionScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/pa/AbstractNewPAScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/pa/NewExchangeScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/pa/NewFunctionalScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/pa/NewScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/sa/AbstractNewSAScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/sa/NewExchangeScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/sa/NewFunctionalScenarioAdapter.java
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/sa/NewScenarioDiagramAdapter.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/NewScenarioRepresentationAction.java
- tests/plugins/org.polarsys.capella.test.explorer.activity.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.explorer.activity.ju/src/org/polarsys/capella/test/explorer/activity/ju/testcases/ScenarioName.java
- tests/plugins/org.polarsys.capella.test.explorer.activity.ju/src/org/polarsys/capella/test/explorer/activity/ju/testsuites/ActivityExplorerTestsSuite.java
name as the scenario
Change-Id: Ice31062b48d399cc42efaaf1e422152e0995f8b8
> [560245] [Activity Explorer] New Scenario diagram does not have the same

- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/DiagramHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ComponentArchitectureBlankRefreshExtension.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/copyformat/keyproviders/TraceabilityKeyProvider.java
- core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/commands/DiagramTransitionRunnable.java
- core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/handlers/AbstractDiagramHandler.java
- core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/handlers/ArchitectureHandler.java
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/InitializationFromExistingDiagramTool.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ModelFC/.project
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ModelFC/ModelFC.afm
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ModelFC/ModelFC.aird
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ModelFC/ModelFC.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/InitializeDiagramInvalidFunction.java
Bug: 560092
Change-Id: If426418f05ae9a545694ed2dc4e7717049d52720
> [560092] Initialize diagram from System Architecture wrongly create some functions

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/actions/AllocationManagementAction.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/.project
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.afm
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.aird
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/AllocationManagementTest.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
- Fix Allocation Management for Component Exchanges to Physical Links
- Add JUnit covering:
-- Functional Exchange to Component Exchange allocation
-- Component Exchange to Physical Link allocation
Bug: 560639
Change-Id: I0177b8d508c1ed412a49e8ef036e9a31c06dfdbe
> [560639] Allocation Management menu does not work for CE to PL

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/delete/DeleteHelper.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.melodymodeller
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/MiscModel.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteDoNotDeletePropertyValue.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteElementTestSuite.java
Bug: 560594
Change-Id: Iac102e1f07efbcde9eaef5b6f2fbe5dc8c61651c
> [560594] Deleting the model element applying a PV deletes this PV when it is applied only on it

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PartExt.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropPhysicalComponent.java
Bug: 560556
Change-Id: Ie3754f856973e96f2720a5252d5f1cf27368bb13
> [560556] Drag and drop of deployed Behavior PC in other PC does not work anymore

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/commandline/RefreshAirdCommandLine.java
Bug: 559825
Change-Id: I6158c4d25e3b239ed57503811face86b12096289
> [559825] Fix closing issue on refresh all

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ide5bcdc3f173cc63f89f28f289e9ac1be280c630
Signed-off-by: Yogaratnam YUGANSAN <yugansan.yogaratnam@gmail.com>
> integrate new Kitalpha

- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.mediawiki
Change-Id: I5294371859a5848bc7e158725189daa7c5f135f3
> [559825] Add an execution example for the migration-post-migration script

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/actions/AllocationManagementAction.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/.project
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.afm
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.aird
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/allocation-management/allocation-management.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/AllocationManagementTest.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
- Fix Allocation Management for Component Exchanges to Physical Links
- Add JUnit covering:
-- Functional Exchange to Component Exchange allocation
-- Component Exchange to Physical Link allocation
Bug: 560639
Change-Id: I0177b8d508c1ed412a49e8ef036e9a31c06dfdbe
> [560639] Allocation Management menu does not work for CE to PL (#107)

- core/plugins/org.polarsys.capella.core.compare/src/org/polarsys/capella/core/compare/CapellaScope.java
- tests/plugins/org.polarsys.capella.test.platform.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/DiffmergeExternalReferences.java
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testsuites/PlatformTestSuite.java
Bug: 560715
Change-Id: I63676ea870a5e8bcc6969fd612701e9bcc6fae04
Signed-off-by: Olivier Constant <olivier.constant@thalesgroup.com>
> [560715] Avoid inter-resource set dependencies with platform plug-in elements

- core/plugins/org.polarsys.capella.core.commandline.core/src/org/polarsys/capella/core/commandline/core/DefaultCommandLine.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/cmdline/MigrationCommandLine.java
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.mediawiki
- Remove useless error messages and update doc
Change-Id: I01e623e926200b685cb822ee8d1ccef7560fe649
> [560828] [CommandLine] Add some evolutions for command line argument

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I9434c524d3424df2faaa12b8f345b35de674c82e
> [releng] Update Sirius version to 6.3.1-S20200320-102312

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Id416b038c438a17b7230f0ebcd81334430b853d9
> [releng] Update to Kitalpha 1.4.1 DEV0

- core/plugins/org.polarsys.capella.core.projection.common/src/org/polarsys/capella/core/projection/common/ProjectionMessages.java
- core/plugins/org.polarsys.capella.core.projection.common/src/org/polarsys/capella/core/projection/common/messages.properties
- core/plugins/org.polarsys.capella.core.projection.interfaces/src/org/polarsys/capella/core/projection/interfaces/generateInterfaces/Rule_ComponentExchange_Interface.java
- core/plugins/org.polarsys.capella.core.projection.scenario/plugin.xml
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/es2is/ES2ISExt.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/es2is/rules/Rule_Event.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/es2is/rules/Rule_InstanceRole.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/es2is/rules/Rule_Scenario.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/esf2esb/rules/Rule_Event.java
- tests/plugins/org.polarsys.capella.test.projection.ju/model/testInterfacesFromAllocatedFunctions/testInterfacesFromAllocatedFunctions.aird
- tests/plugins/org.polarsys.capella.test.projection.ju/model/testInterfacesFromAllocatedFunctions/testInterfacesFromAllocatedFunctions.melodymodeller
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.melodymodeller
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionsTestSuite.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2IS_01.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2IS_02.java
Change-Id: I252488ebbb3bd1bdc3e9bbf124e55b32900eba15
> [561361] ES2IS and Interface generation consistency

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/extension/style/PartComponentStyleConfiguration.java
Allow style customization on icon path.
Bug: 560962
Change-Id: If36c4fbe879da157916b5f38c3c2c230ca9aeffb
> [560962] Check is show icon and is custom icon

- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceQuery.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchMatchEntry.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchMatchEntryLine.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchQuery.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResult.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultLabelProvider.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultPageHandlerReplaceSelected.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultTreeContentProvider.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForAttributeItem.java
Change-Id: If2630ab9af762e77519dce9d2579c6ceb59bf4b3
> Add the ability to search in list of String

- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchConstants.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchPage.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettingsHistory.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractCapellaSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaLeftSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaRightSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CheckboxFilteredTree.java
previous selected feature/class
Change-Id: I7de2995f1c73f46334a61df5a1de4c1585c2696d
> Using filtered text field on class/feature search criteria deselects the

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/commandline/RefreshAirdCommandLine.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/RefreshDiagramJob.java
Change-Id: Ia2adb056cfa1866a5290096723861184cf69ae49
Signed-off-by: Yogaratnam YUGANSAN <yugansan.yogaratnam@gmail.com>
> [559825] Rework on RefreshRepresentation Commandline

- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.mediawiki
Change-Id: Ie52e58af4c7709f80711942ec4278bf9ee014a7e
Signed-off-by: Yogaratnam YUGANSAN <yugansan.yogaratnam@gmail.com>
> [559825] Update comandline doc

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Idaabeb4be9974b647339456bedb831275118db93
> [releng] Update Sirius version to 6.3.1-S20200403-185919

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Signed-off-by: Felix Dorner <felix.dorner@gmail.com>
> [releng][oomph] Setup fine tuning

- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchConstants.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchPage.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettings.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettingsHistory.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractCapellaSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaLeftSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaRightSearchForContainerArea.java
- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/ClassContentProvider.java
the history
Change-Id: If4c239822e3c9dc0985f2a089fed04366f44be12
> Improve class filters and add them to search history

- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.2. Migration and Post-Migration script example.mediawiki
Bug: 559825
Change-Id: Iaac583de2cc224b51904770734cd5eca4c178950
Signed-off-by: Yogaratnam YUGANSAN <yugansan.yogaratnam@gmail.com>
Change-Id: Iaac583de2cc224b51904770734cd5eca4c178950
> [559825] Update commandline documentation (#178)

- tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/DiagramCreation.test
- tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/MoveRepresentationInActivityExplorer.test
- tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/OpenClose.test
- tests/plugins/org.polarsys.capella.test.rcptt/CopyPasteCut/CutDiagramElements.test
- tests/plugins/org.polarsys.capella.test.rcptt/DiffMerge/LocalFragmentedModel.test
- tests/plugins/org.polarsys.capella.test.rcptt/InnerDiagrams/DeleteSystemFunction.test
- tests/plugins/org.polarsys.capella.test.rcptt/Library/AccessPolicyRecRpl.test
- tests/plugins/org.polarsys.capella.test.rcptt/Migration/CheckAFMFilePresenceAfterMigration.test
- tests/plugins/org.polarsys.capella.test.rcptt/Patterns/MultiApplyPatternFromAnotherProject.test
- tests/plugins/org.polarsys.capella.test.rcptt/Patterns/speficHelpers/PatternsHelper.ctx
- tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileActions.ctx
- tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/RecRpl.test
- tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserDoubleClickOnElement.test
- tests/plugins/org.polarsys.capella.test.rcptt/Sequence/FunctionalExchangeWhenAllocationWithoutTarget.test
- tests/plugins/org.polarsys.capella.test.rcptt/Sequence/LifelineDeletion.test
- tests/plugins/org.polarsys.capella.test.rcptt/Sequence/PrePostConditionDeletionImpactAnalysis.test
- tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Complex.test
- tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Simple.test
- tests/plugins/org.polarsys.capella.test.rcptt/ValidationProfile/ProjectConfiguration.test
- Delete dialog has been renamed
- Migration dialog has been renamed
- Transition Preference has been renamed
- Creation of scenario on Activity explorer
- Preferences are now set as expected at startup
Change-Id: I7576a4aefcf339ef3695293555e2b2747e523138
> [tests] Update RCPTT

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
to rebase and merge (not squash)
> IS changes

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I6836dce631f0f48afc8f2a288d5d15a72feee880
> [releng] Update Sirius version to 6.3.1-S20200506-133541

- core/features/org.polarsys.capella.core.mylyn.feature/feature.xml
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I2bd7741d1f2ab608d5a7f9072e0f51f209eb9aa4
> [561513] Add missing feature egit.mylyn

- core/plugins/org.polarsys.capella.core.data.common.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/project/UnkownFeaturesRule.java
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/I_44_Resolver.java
- samples/In-Flight Entertainment System/In-Flight Entertainment System.melodymodeller
- Add validation rule that detects unknown features
Change-Id: Ifa5d9fd6e48cbe5f564e5e0a04050cbb423662f5
> [562458] CapellaSessionHelper resourceSet options are inconsistent

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
Bug: 563087
Change-Id: Ia9055b3c45908685a29ec23426a71fbb4b5461e0
> [563087] Insert/Remove components on IS shows InstanceRoles instead of represented instances

- samples/In-Flight Entertainment System/In-Flight Entertainment System.melodymodeller
Bug: 562458
Change-Id: Iea229832c46c87f7d81ec1a3d00e3dabd551c994
> [562458] Perform Sirius lazy migration on IFE sample model

- samples/In-Flight Entertainment System/In-Flight Entertainment System.melodymodeller
Change-Id: Iea229832c46c87f7d81ec1a3d00e3dabd551c994
> [562458] Perform Sirius lazy migration on IFE sample model (#221)

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/InsertRemoveTool.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XDFBToolsTestingModel/XDFBToolsTestingModel.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/model/XDFBToolsTestingModel.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xdfb/XDFBShowHideFunctions.java
Bug: 562503
Change-Id: If672108c2801c3f8f6a6a9d6b368c017a37de239
> [562503] OAIB Insert Remove Operational Activities wrongly filters activities allocated to actors

- core/plugins/org.polarsys.capella.core.data.common.validation/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.common.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/project/ProjectReferencedLibrariesRule.java
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/I_03_Resolver.java
- core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/handlers/ManageReferencedLibrariesHandler.java
- core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/views/libraryManager/referencesManager/ReferencesManagerWidget.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/AbstractCapellaModel.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/CapellaLibraryExt.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/CapellaModel.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/ModelIdentifier.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/properties/LibraryManagerModel.java
- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/properties/ReferencesProperty.java
* [561395] Exception is raised when trying to manage references for a model
with broken reference to a library
Bug: 561395
Change-Id: I2ef8dbbcd7c6e3314bafe16c9bf55c6ba9cb165a
Signed-off-by: Ali AKAR <ali.akar82@gmail.com>
> [561395] Exception is raised when trying to manage references for a model with broken reference to a library (#158)

- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/DDiagramEditPartProvider.java
Change-Id: I79a89621294e9732eeb8c013799b490d02c8dff8
> Fix Title Block CTRL + drag duplication bug

- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/delete/CapellaDeleteActionHook.java
- Deletion of a Title Block cell clears the cell content
- Deletion of a Title Block deletes elements as expected, except for any
referenced Model Elements
Change-Id: If8a26cbcacab8562aa1d7752dfc5ec13d9480bfa
> Fix Deletion of Title Block Elements

- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
Bug: 558032
Change-Id: I5f5d435aa060dc718cb38c39b4c25f7a51643b21
> [558032] Ctrl+space on Properties on diagrams didn't work

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- doc/plugins/org.polarsys.capella.diagrams.doc/html/Diagrams/diagrams.html
- doc/plugins/org.polarsys.capella.diagrams.doc/html/Diagrams/diagrams.mediawiki
Change-Id: Ic98bf6a0f8c30b55a659d012c21786120a01a808
> Update description of Title Block Tools

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout
Change-Id: I599e9d6c895a5e33f4d402f9c177b62460ef3eb0
> [releng] Update Sirius version to 6.3.1-S20200602-082939

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I0ef816e566f3579769518f3f93c8a0e9e5b807ec
> [releng] Update Kitalpha version to 1.4.1.IT4

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/preferences/TitleBlockPreferenceField.java
- Fix column insertion when no column is selected
Change-Id: I79c1073ff7f54403feaa5666ad0417d6338abc41
> [558032] Fix Column Insertion of Title Blocks

- core/plugins/org.polarsys.capella.core.data.la.validation/src/org/polarsys/capella/core/data/la/validation/logicalComponent/LogicalComponent_RealizedSystemComponents.java
- core/plugins/org.polarsys.capella.core.data.pa.validation/src/org/polarsys/capella/core/data/pa/validation/physicalComponent/PhysicalComponent_RealizedLogicalComponents.java
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/sequence/InsertAllocatedFunctions.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/sortContent/SortContentTestCase.java
Bug: 564195
Change-Id: I30b446eb33f24e65b4e4abcef5f3a24e3c5c340e
> [564195] Fix incompatibilities with for Team for Capella on new enhancements (validation rules and new junits)

- pom.xml
Change-Id: I38c331ebc5f4f8cc01f9ee3716fb9bba240917a0
> [releng] Remove META-INF maven folders on source plugins

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
Change-Id: I9140f81950a5e6d6e7ad2a30b7dd5af4d84a91de
> Title Block edge dissapears in Unsync mode

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/FunctionalChainExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/InvolvementHierarchyGraph.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/FunctionalChainServices.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-cycle-model/.project
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-cycle-model/opd-fcd-cycle-model.afm
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-cycle-model/opd-fcd-cycle-model.aird
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-cycle-model/opd-fcd-cycle-model.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-exchange-tool-cycle-model/.project
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-exchange-tool-cycle-model/opd-fcd-exchange-tool-cycle-model.afm
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-exchange-tool-cycle-model/opd-fcd-exchange-tool-cycle-model.aird
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/opd-fcd-exchange-tool-cycle-model/opd-fcd-exchange-tool-cycle-model.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XDFBDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XFCDDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xdfb/FunctionalChainCycleDetection.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xfcd/InsertExchangeCycleDetection.java
Change-Id: Idb74e9c45b04402ba1b39ca489d0098e1e361445
> [564430] Improve XFCD and OPD cycle detection mechanism

- core/plugins/org.polarsys.capella.core.diagram.helpers/plugin.xml
- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockDeleteHelper.java
- core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
Bug: 558032
Change-Id: Ief7f54e3bd6f368e3a56b72f3da7ed35378a822f
> [558032] Title Block Delete Dialog does not display its children

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
- Remove the use of DialectManager.INSTANCE.refresh from the Title Block
refresh Extension
-- The views are now removed in the extension
- Fix Diagram Title Block hide issue
-- Diagram Title Blocks were hidden whenever a Element Title Block was
hidden
Bug: 558032
Change-Id: Ia599fbdc630363c42c86444754ad153a4cb31303
> [558032] Fix dangling Title Blocks management

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout
Change-Id: I02a7750cf3747fd5ae61e33157d322afcb6bcc2b
> [releng] Update Sirius to 6.3.2

- doc/plugins/org.polarsys.capella.properties.doc/html/Model Editors/TitleBlock.html
- doc/plugins/org.polarsys.capella.properties.doc/html/Model Editors/TitleBlock.mediawiki
Change-Id: Ib5574de17f22d85c40cb48a20f9adeabbd6088f1
> [558032] Update Title block Properties view documentation

- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Bug: 564722
Change-Id: I480c5add34ff6a2e52b54aa95324a23e341611bc
> [564722] Exclude maven directory and its content from product packaging

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Id979c93e2d4882dfff66349f1d0d27031bd7824c
> [releng] Update to Kitalpha IT5-1

- Jenkinsfile
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Add also a Jenkins file for build, with migration agent
Change-Id: I338905f4bef22992ffdd8152f395aa8ecc9bf3d5
> [releng] Update 1.2.x target platform with latest cots

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
Bug: 558032
Change-Id: Ie3d9e523d9496ca57e64cfd8aaa001cd7a6f4002
> [558032] Fix Show/Hide Title Block Tool

- Jenkinsfile
Change-Id: I338905f4bef22992ffdd8152f395aa8ecc9bf3d5
> [releng] Use ui-test-agent custom pod

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I1c9d2b278fcde81f8f1246a593ccbce022bb0b65
> [releng] Update TP to Kitalpha 1.3.3.202007201324

- core/plugins/org.polarsys.capella.core.projection.common/src/org/polarsys/capella/core/projection/common/TransitionHelper.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/commands/IStoISCommand.java
Change-Id: I3bb6b46245059b83cec2413048191cea607c671e
> IS initialization menus are available on upper (ex Capability)

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I1ba3392276c3a7cdfcfd7dd3aa1c35d215630a27
> [releng] Update Sirius to 6.3.3-S20200806-045005

- core/plugins/org.polarsys.capella.core.validation.ui.ide/src/org/polarsys/capella/core/validation/ui/ide/quickfix/DanglingReferenceResolver.java
Bug: 565878
Change-Id: I65cfa9faab01d96a3cf2c7192f7963bcfe75f02c
> [565878] Quickfix for EMF.4 and EMF.16 doesn't work

- core/plugins/org.polarsys.capella.core.projection.common/src/org/polarsys/capella/core/projection/common/TransitionHelper.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/commands/IStoISCommand.java
Change-Id: I34a9d8b352b3159e52d28aa44bed197e0a0284a2
> IS 2 IS added menu when selecting Capability/Capa Realization, Cap. Realiz.pkg architectures

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ifbfea93ad523d245b124c669412aa07e67d90395
> [releng] Update Sirius version to 6.4.0-S20200731-093506

- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/UnsyncronizedSemanticBrowser.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
unexpected way
Bug: 566031
Change-Id: I2b909eeaa1fd05fb4ff868bcffa8da1375d80747
> [566031] Semantic Browser in unsynchronized mode changes content in an

- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/core/validation/constraint/UniqueInvolvementConstraint.java
- core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/ctx/services/CapabilityExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/CapabilityRealizationExt.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/.project
- tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.afm
- tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.melodymodeller
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/CapabilityExtTestCase.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.melodymodeller
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.melodymodeller
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dcov/Rule_DCOV_07.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_40_OnCapability.java
Bug: 566245
Change-Id: Ibc00914baeab6834f745ce31790b3b830fd9c5fb
> [566245] Validation rules I_40 and DCOV_07 are disabled in some models

- Jenkinsfile
Change-Id: I254d1f2316eafbbdf2d134f9f9f498a782117331
> [Releng] Launch Sonar on Pull requests to have Sonar analysis on new code

- Jenkinsfile
Change-Id: I133e57095cbf9ad7635675cdb013cee12a0f2f88
> [Releng] Add again the mistakenly removed -Pfull

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DragAndDropServices.java
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/IDBDiagram.java
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/Component-DragAndDrop/.project
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/Component-DragAndDrop/Component-DragAndDrop.afm
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/Component-DragAndDrop/Component-DragAndDrop.aird
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/Component-DragAndDrop/Component-DragAndDrop.melodymodeller
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/idb/DragAndDropComponents.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/IDBDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropOABActors.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropXABComponents.java
Component Drag and Drop in LAB, PAB, IDB diagram having as target a
Component Package is not possible
- Fix the behavior for LAB, PAB and IDB diagrams
- Add JUnits
Change-Id: Ic9874106a7dd869122466040e59a4b9efc6d2e1e
> [566413] Component Drag and Drop is not possible in some valid scenarios

- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/common/SimpleResolver.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2ES_01.java
Bug: 566412
Change-Id: I9a4dca00cc097611e425874785f37f5d9cf14e57
> [566412] Fix junit regression from 566412

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I1ca545aafc95399c2eca47a7820a416229ff2ad7
> [releng] Update Sirius version to the 6.3.3 release

- Jenkinsfile
Change-Id: I797e9694e046fa76d32f89379730bd9b37c045ad
> [releng] Add dynamic pull request labels for current build status

- common/plugins/org.polarsys.capella.common.tools.report.appenders.reportlogview/src/org/polarsys/capella/common/tools/report/appenders/reportlogview/handler/SaveLogHandler.java
- core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/sections/DiagramTitleBlockContainerSection.java
- core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/sections/ElementTitleBlockContainerSection.java
- core/plugins/org.polarsys.capella.core.data.cs.ui.quickfix/src/org/polarsys/capella/core/data/cs/ui/quickfix/resolver/SwitchIsActorIsHumanFlag_Resolver.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DWF_DF_16_Resolver.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DWF_DF_18_Resolver.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/RemoveSequenceLinksAssociationsResolver.java
- core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/fa/services/BusPatternHelper.java
- core/plugins/org.polarsys.capella.core.data.interaction.ui.quickfix/src/org/polarsys/capella/core/data/interaction/ui/quickfix/resolver/AddInvolvedElementsResolver.java
- core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/src/org/polarsys/capella/core/data/pa/ui/quickfix/resolver/PhysicalComponentNatureToBehaviorResolver.java
- core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/src/org/polarsys/capella/core/data/pa/ui/quickfix/resolver/PhysicalComponentNatureToNodeResolver.java
- core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/views/libraryManager/accessPolicyManager/AccessPolicyLabelProvider.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/WriteCapellaElementDescriptionSAXParser.java
- core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/CapellaElementInDescriptionExistanceCheck.java
- core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/CapellaElementInDescriptionNameCheck.java
- core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/DeleteInValidHyperLinkInDescription.java
- core/plugins/org.polarsys.capella.core.preferences.project.configuration/src/org/polarsys/capella/core/preferences/trasferers/WizardPreferencesTransfererExportPage.java
- core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/preferences/transferer/WizardPreferencesTransfererExportPage.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
- core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/handlers/CapabilitiesHandler.java
- core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/actions/EPFValidationAction.java
- ext/detachment/plugins/org.polarsys.capella.detachment.version.precondition/src/org/polarsys/capella/detachment/version/precondition/impl/VersionChecker.java
Only fixes with no API changes. Some remaining blocking have to be fixe
on master branch
Change-Id: I8859956c879fd7883f63ad9ea46c9a201a266535
> [sonar] Fix blocking issues on Sonar

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
rule
Change-Id: Ib65ac71a3ea8c312cca0ac30e7c963a87fe08fbc
> [566413] IDB Component Drag and Drop does not obey unique root component

- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/common/SimpleResolver.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2ES_01.java
Bug: 566412
Change-Id: I9a4dca00cc097611e425874785f37f5d9cf14e57
> [566412] Fix junit regression from 566412 (wrong id)

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- tests/plugins/org.polarsys.capella.test.table/model/SF-OA/SF-OA.melodymodeller
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/StateModeTableTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/StateModeTableTestSuite.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/TableStateModeFramework.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/testsuite/TableTestSuite.java
Change-Id: Ic9c2bac81f4872f23c774583cd03e001a8c5d7c3
> [566538] Impossible to remove the state/modes of a Capability in a State Machine and Capability Function Matrix

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/constants/ColorNameConstants.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/EOLE_AF_UC/EOLE_AF_UC.aird
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/ColorNameConstantsTest.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XBDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xfbd/XFBDBlueBold.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/SkeletonHelper.java
Bug: 566601
Change-Id: I68a18e4d1c33f2813f4d403841c4e2fdf40372ed
> [566601] xFBD diagram on actor doesn't highlight function as blue

- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Change-Id: I3adf8da20fb930a81efee35eb79cf7ee11ff150c
> [Releng] Add the mistakenly removed zip steps

- core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/SearchForItemCache.java
viewpoints
Change-Id: I1d8e0e457fbc787958f8204be59dc54b77546034
> [566777] Capella Search fails during the indexation of invalid

- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/actions/DiagramOpenAction.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/view/SiriusSemanticBrowserView.java
Semantic Browser
Bug 566828
Change-Id: I6c11b8a42ecc9623a57116055acb67cfd7bc6f0b
Signed-off-by: Ali AKAR <ali.akar82@gmail.com>
> [566828] Cannot open at once a selection of representations available in

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/IDiagramNameConstants.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/StateModeTableTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/StateModeTableTestSuite.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/TableStateModeFramework.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/ContextualStateModeTableTestSuite.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/ModeTableTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/StateTableTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/TableContextualStateModeFramework.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/testsuite/TableTestSuite.java
State Machine Matrix
Change-Id: I8e73125e82867bfc4735c35f6810e8111fd5d52c
> [566984] Remove mode/states from function in Capability Function and

- Jenkinsfile
- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
- Linux version
- Mac version
- Windows version
Change-Id: I5fab7f9bf8c897d583783b32c251fd1848b48809
> [releng] Bundle openjdk-14.0.2 with Capella

- doc/plugins/org.polarsys.capella.ui.doc/.settings/org.eclipse.core.resources.prefs
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Change-Id: If3cdd90776d9587f76f7639315b7f743b6b936be
> [doc] Update documentation in regards to embedded openjdk-14.0.2

- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
- releng/plugins/org.polarsys.capella.rcp.product/capella.product
- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I370b8dff526a8f1bc1eb1b814ec6b53d3f03e63f
> [releng] Modify .product JDK required version to 14

- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/TransitionCommandHelper.java
Bug: 567633
Change-Id: I645e8cf85d2b2b4472741acb3f5b3a0281e8347e
> [567633] Menu System->LogicalSystem not enabled on Part

- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/commands/ESToISCommand.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/helpers/ScenarioInvolvementSynchronizer.java
Change-Id: I5a584f7edf37e05290880e7e22fdd3145a64764c
> [567469] Fix circular references after transition

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
Bug: 567679
Change-Id: Ib232a3b2d11d064c72829dd401cb4cb248071807
> [567679] EI creation inside Interface in IDB/CDB diagram in unsynchonized mode does not work and raise EvaluationException error

- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/providers/MDEAdapterFactoryLabelProvider.java
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/CapellaAdapterHelper.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/CloneAction.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/move/representation/MoveRepresentationMenuManager.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaNavigatorLabelProvider.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenRepresentationsAction.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/RenameRepresentationAction.java
- core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
- core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/TabbedPropertiesLabelProvider.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
These cases have been detected using Team For Capella after a shutdown
of the server with a session opened.
Bug: 566437
Change-Id: I9a4a3e292a0024efb9fdf7f13e1ce2c030003e0b
> [566437] Use IllegalStateExceptionQuery where it is necessary

- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/commands/ESToISCommand.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.melodymodeller
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionsTestSuite.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_01.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_02.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_03.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_04.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_05.java
- bug fix on multiple select
Change-Id: Ia86f30fdded9299734533f475057fbadf5d4f4e2
> [567469] [JUNITS] Transition reference

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
Bug: 567866
Change-Id: Ib39bcc75542303cb3ad6572e751806035ac36eba
> [567866] LogicalFunction creation on LDFB is KO if the function is allocated in a LC

- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/FunctionCapabilityInvolvementRule.java
- tests/plugins/org.polarsys.capella.test.transition.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.melodymodeller
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/ReferencedScenarios_02.java
- disabled the transition of
AbstractFunctionAbstractCapabilityInvolvement from PA to EPBS
Change-Id: I80435457b3bb2cad8fc3a83d9578eb9bea12116e
> [567857] Cannot save model after IS transition from PA to EPBS

- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceHelper.java
Bug: 567412
Change-Id: Iba9bc5121df34002b37f3af83dac0fe5428ae2f6
> [567412] Revert the change to migrate .melodyconnector to .capellaconnector

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/Messages.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/messages.properties
- core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java
This message is displayed when a representation is about to be deleted.
Change-Id: Ib5dd66e0e145d40a4737999c697fc778b2062a44
> [567246] Add a warning message in the DeleteCapellaElement dialog box

- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/BasicCapellaDeleteCommand.java
Bug: 567246
Change-Id: Ie0231ead659bdfbc85c5ba5259f5aab680b4a37c
> [567246] Without an OK Status the delete doesn't complete

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ia23fa8ee53a6a6c310f18a0ec33fbf1a98f7b1f4
> [releng] Update to Amalgam 1.12.0-S20201020

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I4db8eaf6fe34bd836baf3c10491de2edcbefd90c
> [releng] Use Diffmerge 0.13.0-M4

- core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/ScenarioCache.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ScenarioRefreshExtension.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ScenarioRefreshExtensionProvider.java
Signed-off-by: Nathalie Lepine <nathalie.lepine@obeo.fr>
> [563193] Capella Diagram Performance issues

- common/plugins/org.polarsys.capella.common.platform.sirius.customization/src/org/polarsys/capella/common/platform/sirius/customisation/uicallback/SiriusUiCallBack.java
- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ib5397cecca70421482fe8aba024bb3a43836b075
> [releng] Update target platform to Sirius

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaNavigatorContentProvider.java
Bug: 568294
Change-Id: Ic691df4b5722a026b3b3467407a44c1a49c52429
> [568294] A newly created element may not be focused by default

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/MoveRepresentationsAction.java
Bug: 567909
Change-Id: I361bd317f8c03bea2a283fa22861b27f210be952
> [567909] Fix IllegalStateException

- tests/plugins/org.polarsys.capella.test.commandline.ju/src/org/polarsys/capella/test/commandline/ju/testcases/CommandLineRefreshAirdTest.java
Bug: 567909
Change-Id: I0c50aa305b725af7af42ded34c5de83c8383fb99
> [567909] Fix Commandline Junit regression

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Sync .setup to capella tpd for master branch
> [releng][oomph] Sync target platform

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/IImageKeys.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/handlers/GotoRelatedElementsHandler.java
Bug: 568530
Change-Id: I773e3c7dd306e7b23fbf70c402da233dbef1d35c
> [568530] Icon for the menu Show Related Element(s) in Project Explorer disappears

- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/TransitionCommandHelper.java
In the following cases, the Transition of SM raises errors:
- On Operational Analysis
- On Components without State Machine
Bug: 568561
Change-Id: Iab50752d85d8ecad0b89bdc71327f4a149c3a54a
> [568561] Transition of State Machine raises error in some cases

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentPkgExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PartExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/queries/csServices/GetABInsertComponentActor.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/context/SessionContext.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/.project
- tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.afm
- tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.aird
- tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.capella
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/AbstractDndTest.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndOA.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndPA.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndSA.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/DnDTestSuite.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/testsuites/main/NavigatorUITestSuite.java
constraints
- Fix Drag and Drop behavior causing the problem
-- Component Drag and Drop
-- ComponentPkg Drag and Drop
-- Part Drag and Drop
- Extract and delegate the Drag and Drop logic to their respective
source *Ext classes
- Use the same logic in both Project Explorer and Diagramd
- Add unitary tests
Change-Id: I7a4a400baa60e0b7300494e4522e24adc0247b05
> [568684] RPL instantiation does not respect Physical Component

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I03950f8f9aca2649fa95008c43da420ecac1a438
> [releng] Update Kitalpha version to 5.0.0-S202011101656

- core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
Bug: 568644
Change-Id: I1f61a534b04b29ef9dfe8f181912aec863d1a53f
> [568644] [Richtext] In read-only mode, users cannot see the full description

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForInstanceRole.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForPartsAndComponents.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelEditingDomainListener.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/NamingHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
Right now, it works only for Part.
Bug: 568583
Change-Id: Id001482117abf9783144541e378b09306db82309
> [568583] Renaming the Instance Role should rename the Represented Instance and vice-versa for all scenario kinds

- core/plugins/org.polarsys.capella.core.data.interaction.validation/plugin.xml
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.html
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.mediawiki
- Remove use of 'part' term
Change-Id: I7c1546a1ba84ca6ce06bd91f380c86bacf02ce85
> [568560] Update validation rule documentation

- core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/service/FieldEditorPropertyPreferencePage.java
- core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/service/PropertyStore.java
- tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileActions.ctx
- tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileSuite.suite
- tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfilesStep5.test
Bug: 568312
Change-Id: I096ac6e6258a315cb309f3fd511aae775c33f638
> [568312] Fix Apply button on Project Page Properties

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/RenameResourceAction.java
- doc/plugins/org.polarsys.capella.ui.doc/html/03. First steps with Capella/3.7. How to rename a Capella Project.html
- doc/plugins/org.polarsys.capella.ui.doc/html/03. First steps with Capella/3.7. How to rename a Capella Project.mediawiki
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/.project
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].afm
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].capella
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/fragments/[OA].airdfragment
- tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/fragments/[OA].capellafragment
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/rename/RenameModelTestSuite.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/rename/RenameSpecialCharTestCase.java
characters
- Fix resource reference renaming issue
- Fix file reference renaming issue in element description
- Update renaming documentation
- Add JUnit
Change-Id: Ie90f5d46a11b90f269dc1a12c8c991ac3782f43e
> [568983] Project renaming fails for names containing non-alphanumerical

- Jenkinsfile
- pom.xml
Change-Id: I2c3b60849912318019d0d8b92f6385c3b19c9e35
> [releng] Enable jacoco coverage on tests

- core/plugins/org.polarsys.capella.core.model.handler/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceNamingHelper.java
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/Messages.java
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/messages.properties
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/RenameResourceAction.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.project/src/org/polarsys/capella/core/platform/sirius/ui/project/internal/WizardNewProjectCreationPage.java
- core/plugins/org.polarsys.capella.core.preferences.project.configuration/src/org/polarsys/capella/core/preferences/configuration/project/WizardProjectCreationPage.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/CapellaResourceNamingHelperTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
containing special characters
- Fixed the issue
- Added JUnit
Change-Id: Idd33c678844f1f017ee282338cb30d15d95d465d
> [569062] Forbid Project creation or Resource renaming for names

- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/TraceTreeSelectionDialog.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/providers/CapellaModelFilter.java
Change-Id: I518148c9d1f810687d6cabe1afded19943a2694e
> [567249] Enter enabled on selecting an element

- core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
Change-Id: I999fec25beea118e1077ab7bb5d322ee6836057d
> [568858] Fix wrong namespaceUri for the validation rule

- core/plugins/org.polarsys.capella.core.transition.system.topdown/plugin.xml
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/IntramodelTransitionCommand.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/handlers/transformation/TopDownTransformationHelper.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityExtendRule.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityGeneralizationRule.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityIncludeRule.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityRule.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/CapabilityInvolvementRule.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/oa/capability/EntityRule.java
- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/interaction/AbstractCapabilityExtendRule.java
- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/interaction/AbstractCapabilityIncludeRule.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/AllProjectionModels/AllProjectionModels.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/AllProjectionModels/AllProjectionModels.capella
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/ModelLaPa.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/ModelOaSa.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/la/ActorTransition.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/la/CapabilityTransition.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/oa/CapabilityTransition.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/sa/CapabilityTransition.java
Bug: 569167
Change-Id: I2c8ca3a6a67a39270cffd19ac2b32bb48c640351
> [569167] Capability transition does not work for involved components/actors and other capability relations

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I69b3af4a9c58e9e6264dc69b0eecc12d01c49be3
> [releng] Update Kitalpha version to 5.0.0-S202011241439

- core/plugins/org.polarsys.capella.core.transition.system.ui/META-INF/MANIFEST.MF
- doc/plugins/org.polarsys.capella.viewpoint.doc/META-INF/MANIFEST.MF
Change-Id: I1039b1066e0783223b073f2f5008ba5cb53517fd
> [releng] Add missing Bundle-RequiredExecutionEnvironment

- tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/MoveRepresentationInActivityExplorer.test
- tests/plugins/org.polarsys.capella.test.rcptt/DiffMerge/LocalFragmentedModel.test
- tests/plugins/org.polarsys.capella.test.rcptt/Menu/MoveRepresentation.test
Change-Id: Icee1dd10eef42e901d7264942ecb2417f9b7c3c1
> [567909] Fix rcptt tests

- Jenkinsfile
- releng/plugins/org.polarsys.capella.rcp.product/capella.product
- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Change-Id: Id3e4e0202bade6d77f04394fa1cd87215e707d4f
> [releng] Keep executable permissions for linux and macOS bundles

- common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/subcommands/handlers/SelectionCommandHandler.java
- common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/persistence/ConfigurationInstance.java
- common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/persistence/LogLevel.java
- common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/persistence/OutputConfiguration.java
- common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/registry/ReportManagerRegistry.java
- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/impl/AbstractContentProvider.java
- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/services/commands/AbstractLocateInWorkbenchPartHandler.java
- core/plugins/org.polarsys.capella.core.commandline.core/src/org/polarsys/capella/core/commandline/core/AbstractCommandLine.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/CapellaWorkbenchAdvisor.java
- core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/internalization/l10n/CustomPreferencesMessages.java
- core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/internalization/l10n/CustomPreferencesMessages.properties
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/ModelDropTargetAdapter.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/RemoveHiddenElementsHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/refactoring/WorkspaceImagePathChange.java
- core/plugins/org.polarsys.capella.core.ui.fastlinker/src/org/polarsys/capella/core/ui/fastlinker/SendToFastLinkerCommandHandler.java
- legacy/plugins/org.polarsys.capella.common.mdsofa.common/src/org/polarsys/capella/common/mdsofa/common/misc/Couple.java
The following rules are taken into account:
- Method should not always return the same value.
- Replace "clone" implementation by constructor
- Rename fields having the same name as methods or fields coming from super classes
- Use try-with-resources structure
2 following methods should be fixed on DiffMerge:
org.polarsys.capella.core.compare.CapellaMatchPolicy.clone()
org.polarsys.capella.core.transition.common.ui.handlers.merge.DiffCategoryProxy.clone()
Change-Id: Ia8df1c67add6c6e97ab4c3dc0a9f8cb3a6b21cbf
> [Sonar] Fix Sonar blocking issues

- core/plugins/org.polarsys.capella.core.compare/src/org/polarsys/capella/core/compare/CapellaMatchPolicy.java
- core/plugins/org.polarsys.capella.core.transition.common.ui/src/org/polarsys/capella/core/transition/common/ui/handlers/merge/DiffCategoryProxy.java
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- Only merge if
https://git.eclipse.org/r/c/diffmerge/org.eclipse.emf.diffmerge.core/+/174124
will have been merged
Change-Id: I85005b4c986a3056fb66a313bb61dcca48969769
> [Sonar] Fix java:S2975

- core/plugins/org.polarsys.capella.core.compare/src/org/polarsys/capella/core/compare/CapellaMatchPolicy.java
- core/plugins/org.polarsys.capella.core.transition.common.ui/src/org/polarsys/capella/core/transition/common/ui/handlers/merge/DiffCategoryProxy.java
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
This reverts commit 6a93d88e8ea754cacee9ae998ae9a683ec433575.
> Revert "[Sonar] Fix java:S2975 and integrate DiffMerge 0.14.0-M1"

- core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/src/org/polarsys/capella/core/data/common/ui/quickfix/resolver/DWF_SM_06Resolver.java
- core/plugins/org.polarsys.capella.core.data.common.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/statetransition/MDCHK_State_Mode_Siblings.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_sm/Rule_DWF_SM_16.java
Change-Id: Iadf8e9da0ea0398f5c6532c68a2ca6d07713e0ae
> #2038 New validation rule to detect Mix of Mode/State in StateMachine

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
(for Monopart)
Change-Id: I721ec8cce4184268cf88281169576f1b0a2f685b
> #2041 Constraints on elements in diagrams should be saved homogenous

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/CapellaWorkbenchAdvisor.java
Change-Id: Ia02fe62c69bd5ced26d17e3db45ffcee8846c623
> #2047 Version Tag not correctly extracted

- core/plugins/org.polarsys.capella.core.data.common.ui.quickfix/src/org/polarsys/capella/core/data/common/ui/quickfix/resolver/DWF_SM_06Resolver.java
- core/plugins/org.polarsys.capella.core.data.common.validation/plugin.xml
Fixes #2038 
Change-Id: I31e41ed770665408a91583b385631726220ab7a3
> #2038 Fix validation message and QF

- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
Change-Id: I2ad0b3f99a45e47fc88703d6865af2a37db6f7be
> [doc] Fix mediawiki Installation Procedure

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/FunctionalChainServices.java
Change-Id: I86e2f73779dd80ee775b50be956a3fb9f5458603
> #2054 Reset of FunctionalChain style can unexpectedly set diagram dirty

- core/plugins/org.polarsys.capella.core.semantic.queries/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ConstraintModelElements.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
Change-Id: I43d9a4fb5dd77946708f1b9259086b10e82c0c53
> #2041 Constraints

- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/common/AbstractStateRule.java
- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/common/AbstractStateRule.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Context_I01/Context_I01.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Context_I01/Context_I01.capella
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/Context_SM01_03.java
Resolves #2055
Change-Id: I7f48e97911f4fc5ff1c16a78f1596e5461ca9ce0
> #2055 The transition should include in its scope state/mode's do activities, entries, exits involving functions or exchange items

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
Change-Id: I4f7a85f73df5908e2cae8a7760d0b40ee17ec3d4
> #2034 [cleanup] D&D from Region to Region from review

- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/common/AbstractStateRule.java
- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/common/AbstractStateRule.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/Context_I01/Context_I01.capella
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/Context_SM01_03.java
Resolves #2055
Change-Id: I1431c22ff40304714f59a631d991f5660287228f
> #2055 The transition should include in its scope state/mode's available functions

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/CapellaMoveHelper.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/SkeletonHelper.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/model/GenericModel.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/SemanticDnd/.project
- tests/plugins/org.polarsys.capella.test.model.ju/model/SemanticDnd/SemanticDnd.afm
- tests/plugins/org.polarsys.capella.test.model.ju/model/SemanticDnd/SemanticDnd.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/SemanticDnd/SemanticDnd.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDEMFConsistency.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDMixedStatesModes.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDSemanticConsistency.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dnd/DnDTestSuite.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/SemanticDnd.java
Fixes #2075
Change-Id: Ifb99c541df7c3e796663e49b79b5ba2cb7187028
> #2075 Drag doesn't display not-allowed mouse cursor

- core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/StateTransition_RealizedStateTransition.java
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/StateTransition_RealizingStateTransition.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/StateTransition_realizedStateTransition.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/StateTransition_realizingStateTransition.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
Resolves #2073
Change-Id: Ie902b951d0a9a855658d9f5d58eb4081764ecc30
> #2073 [Semantic Browser] Add SB queries for Realized and Realizing State Transition

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- Update copyright fixer template to EPL 2.0
- Targlets / Target Platform
Signed-off-by: Felix Dorner <felix.dorner@gmail.com>
> [releng][oomph] Update setup

- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/state_machines/ValidationRules.html
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/state_machines/ValidationRules.mediawiki
Fixes #2085 
Change-Id: I88459467d9b684b77a7a548f05c532e320ed89d2
> #2085 Update doc with State Machine Validation Rule

- doc/plugins/org.polarsys.capella.core.ui.intro/intro/firststeps-doc.xml
- doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.mediawiki
- doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.0.x_to_1.1.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.0.x_to_1.1.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.mediawiki
Fixes #2071 
Change-Id: I91d30f4c4d7a2ecb08f1cd563371104237272b17
> #2071 Deprecated polarsys links updated with Eclipse

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/constants/IFilterNameConstants.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/.project
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.afm
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.aird
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.capella
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/model/InternalLinks.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/testsuites/DiagramFiltersTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksLAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksLDFB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksPAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksPDFB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksSAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksSDFB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksLAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksPAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksSAB.java
- tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/XABDiagramFiltersTestSuite.java
- tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/identifier/ToolAndLabelCoherenceTest.java
Change-Id: I45dd91bae017e07ec388e55f64280ce6c05de9a6
> #2088 Add filters for Functional Chains and Paths internal links

- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/SkeletonHelper.java
Change-Id: I55b1711d33a5bfd6f0e16dcb0bd55ce13c42e783
> #2075 Fix failing junit

- doc/plugins/org.polarsys.capella.core.ui.intro/intro/firststeps-doc.xml
Change-Id: Iafbf739ae47bec7f86f318b68b3b71c32b82744b
> #2071 Deprecated Polarsys

- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintAssignmentRule_Resolver.java
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Resolver.java
- core/plugins/org.polarsys.capella.core.data.core.validation/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintAssignmentRule.java
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintLocationRule.java
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ModelElementConstraints.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
Fixes #2024 
Change-Id: Ia7e224dc5f32fd26cdbd7112c64a78db3e120486
> #2024 Constraint changes

- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintAssignmentRule.java
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintLocationRule.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.html
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.mediawiki
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_58.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_59.java
> #2024 Constraints changes, help, junits

- core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/statetransition/MDCHK_State_Mode_Siblings.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_sm/Rule_DWF_SM_16.java
Fixes #2038
Change-Id: I19479a776f0c748183e64dcb3ea68602adb52a6a
> #2038 Final States in State Machine raise DWF_SM_16

- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/cmdline/MigrationCommandLine.java
- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/RepresentationHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/RefreshDiagramsCommandHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/SessionHelper.java
- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnDisabledProject.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnEnabledProject.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnNonCustomizedProject.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/SpecificSettings.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/DiagramActionsTestSuite.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/GuiActions.java
https://download.eclipse.org/sirius/updates/stable/6.5.0-S20210225-102754/2020-06/
> [releng] Update Sirius version to 6.5.0-S20210225-102754

- releng/plugins/org.polarsys.capella.rcp/about.ini
Change-Id: Ie113efa9f026b180164615f10ff62a249d1890f1
> #2119 Add Capella feature on About Dialog

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/DeleteHandler.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/plugin.properties
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/plugin.xml
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
- Enable the new Delete Binding in either a Semantic Browser context or
Interpreter view
- Fix error when trying to delete a category in the Semantic Browser
Change-Id: I0b9028e402636b5e5280d6c5f0733dd2eda4d5fc
> #2116 Fix delete binding conflict for Resources and Model Elements

- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/wrapper/CategoryWrapper.java
- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/wrapper/PrimitiveWrapper.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Resolve #2128 
Change-Id: I14a623f16bb3bed3f42c9854ecc3092c7e4b8fce
> #2128 Fix Copy as text for CategoryWrapper and PrimitiveWrapper

- core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteElementTestSuite.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteShowReferencingImpact.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteTest.java
Change-Id: I9a3c49282d210edf0c7040765109c2b049c66be3
> #2131 Delete Wizard improved displaying all impacted elements by default

- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Generator.java
- core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Resolver.java
- core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintAssignmentRule.java
- core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintLocationRule.java
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.html
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/data/ValidationRules.mediawiki
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_58.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_d/Rule_DWF_D_59.java
Fixes #2024 
Change-Id: I060d3285a5584edec28522244eb9a3e186c72543
> #2024 Validation rule DWF_D_58, DWF_D_59 to update in multipart mode

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PhysicalLinkExt.java
- core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/accelerators/PhysicalLinkAcceleratorTest.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/ComponentPkgExtTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/MiscModel.java
Resolve #2133 
Change-Id: Ibb27c05556bf83547cd929c91b178ef8c1a847fb
> #2133 Component Port Allocation is not visible in diagram LAB

- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/TreeAndListViewer.java
- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/data/AbstractData.java
- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/data/TreeData.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dialog/CapellaTreeDataTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Resolves #2140 
Change-Id: I0007773e45808909cc1947a2b7b2037befc157ce
> #2140 Sorted Architecture in transferviewer

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Resolves #2143
Change-Id: I80ce93bc8275af37580f792c30e8813d407039ac
> #2143 Remove NewLine on using CopyAs command

- tests/plugins/org.polarsys.capella.test.model.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/propertyviews/PropertyViewsTest.java
Change-Id: Id55e21c9c530775a41d0df5cb3e3138c90d169a3
> [test] Fix PropertyViewTest

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/RefreshDiagramsCommandHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/SessionHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnDisabledProject.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnNonCustomizedProject.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/SpecificSettings.java
Fix with Sirius https://bugs.eclipse.org/bugs/show_bug.cgi?id=571611
> #2045 Remove duplicated code on Capella

- core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/src/org/polarsys/capella/core/data/pa/ui/quickfix/resolver/PhysicalComponentDeleteDeploymentLinkResolver.java
- core/plugins/org.polarsys.capella.core.data.pa.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.pa.validation/src/org/polarsys/capella/core/data/pa/validation/physicalComponent/PhysicalComponentContainedAndDeployed.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/showhide/ShowHideABComponent.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/DAnnotationPrecommitListener.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/ShowHideComponentExchanges.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/ShowHidePhysicalLinks.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_dc/DWFDCRulesTestSuite.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_dc/Rule_DWF_DC_44.java
Resolves #2146
Change-Id: Id9ae24b597bf8d33faa09412e492a1ccfb6e659b
> #2146 Node PC/Behavior PC contained and deployed inside the same Parent Component

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I9b016f6d6b4971da3e2726adc65cb0ab6cfed6db
> [releng] Update Capella target platform for IT1

- core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
- core/plugins/org.polarsys.capella.core.validation.ui/plugin.xml
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Resolves #2151
Change-Id: I7c786cbe15d3e90a5f629d399c577e4b94ca3285
> #2151 Validate and Copy as text menus are visible on empty selection

- core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/information/services/DataTypeExt.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/DataTypeRealizedInformationTest.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Change-Id: I13a835f4823ab21d1198583e21fb253655993748
> #2149 Realized information source isn't set on DataType from properties

- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceHelper.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/GitConflictHelper.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/.project
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/fragments/SA.airdfragment
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/fragments/SA.capellafragment
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.afm
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.capella
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/.project
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/fragments/SA.airdfragment
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/fragments/SA.capellafragment
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.afm
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/GitConflictHelperTest.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Change-Id: I5c4c071a5eb58caf2a07f449e5ebdc98041e8462
> #2138 Handle when a fragment of a library is in conflict state

- core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/handlers/MigrationPropertyTester.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
- core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/DynamicActionProvider.java
Resolves #2151
- Migrate, Open, Open and Show in Diagram Editor
- Disable Validate action when it contains empty selection
Change-Id: I6c7d64dcb5702a173a5bb5f5ef89df7e12e7e237
> #2151 Disable menus on empty selection

- common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/persistence/OutputConfiguration.java
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/CapellaLoggerConfigTestCase.java
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/JobLogTest.java
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testsuites/PlatformTestSuite.java
Resolves #2165
Change-Id: Ic71837d9fd8ec26e04d4451f89e3248a41ed4511
> [2165] Default Log Configuration deep copy

- samples/In-Flight Entertainment System/In-Flight Entertainment System.capella
Change-Id: I5abcff773f50d3ef6129d6a11aae7d0b60159833
> [releng] Migrate IFE model

- common/plugins/org.polarsys.capella.common.tools.report.appenders.reportlogview/src/org/polarsys/capella/common/tools/report/appenders/reportlogview/LightMarkerRegistry.java
- tests/plugins/org.polarsys.capella.test.commandline.ju/src/org/polarsys/capella/test/commandline/ju/testcases/CommandLineValidationTest.java
Resolves #2174 
Change-Id: Ief2462224b3090bf2a7f8094eceffac8148256ac
> #2174 Resources column empty on validate from cmd line

- doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.mediawiki
- doc/plugins/org.polarsys.capella.doc/toc.xml
Change-Id: I100fd5b07b57acf260f2530e6ce058f46575bd84
> [doc] Add dependency versions reference

- common/plugins/org.polarsys.capella.common.platform.sirius.customization/src/org/polarsys/capella/common/platform/sirius/customisation/SiriusCustomizationPlugin.java
- tests/plugins/org.polarsys.capella.test.commandline.ju/src/org/polarsys/capella/test/commandline/ju/testcases/CommandLineExportRepresentationsTest.java
- tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/CapellaSiriusCustomisationEnabled.java
> #2154 Add support for semantic traceability on exported SVG elements

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ic9b06f2fe25ffb7042f4a325b0ae486a3b561275
> [releng] Update Diffmerge 0.13.1-M2 and Kitalpha IT2

- tests/plugins/org.polarsys.capella.test.model.ju/model/lcdecomposition/lcdecomposition.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/lcdecomposition/lcdecomposition.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcase/LCDecomposition/LCDecompositionAttachDetachCommunicationLinkInterface.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Resolves #2181 
Change-Id: Ie607725b950436b2e2e000701b2b7f36d4b34bfb
> #2181 Test LCDecomposition

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/CapellaSessionHelper.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/Messages.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/messages.properties
- tests/plugins/org.polarsys.capella.test.migration.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.migration.ju/model/Migration.ecore
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/EFactoryTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/MigrationContributionTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/NsPrefixTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/PackageRegistryTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/TestOfTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
> [test] Add some migration framework junit

- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/AllRelatedDiagrams.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/AllRelatedTables.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ContextualElements.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ElementOfInterestOfRepresentations.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ElementOfInterests.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
Change-Id: I8da434a6deeaa29238ef8f1fee5c55e899925377
> [test] Add junits for Representations references in Semantic Browser

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Icd408dbe7c97ca40a23074561688e7379c8bb9ba
> [releng] Update Diffmerge 0.13.1-M3 and Kitalpha IT3

- tests/plugins/org.polarsys.capella.test.rcptt/AllTests.suite
- tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceElements.suite
- tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceManagerWizard.test
[test] Rcptt test for Trace Manager Wizard
Change-Id: I59dd39d54e0c5102e8ff777f920449bef3acc515
> [test] RCPTT test for Trace Manager Wizard

- core/plugins/org.polarsys.capella.core.compare/src/org/polarsys/capella/core/compare/CapellaComparisonMethod.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListener.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForExchangeItemAndExchangeItemInstance.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForInstanceRole.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForPartsAndComponents.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForSequenceMessages.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeBetweenSubsystemModels.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeBetweenVersionsOfSameCapellaT4CModelTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeBetweenVersionsOfSameModelCapellaFile.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeBetweenVersionsOfSameModelTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffMergeTestSuite.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/DiffmergeDomain.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/TransferBetweenModelsCreatedIndepentlyTestCase.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/diffmerge/TransferOfElementsBetweenCapellaProjectAndLibTestCase.java
- tests/plugins/org.polarsys.capella.test.rcptt/Interface/InterfaceDelegation.test
Change-Id: I7b10c157ba4dc793bc67059e266a1fc69f1b49bf
> #2201 Comparison of .capella doesn't work

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Set correcct eclipse and groovy targets, install correct groovy-eclipse for development workspace
> [releng][oomph] Update setup for capella-groovy development

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
https://download.eclipse.org/sirius/updates/releases/6.5.1/2020-06
Change-Id: I3031b8e56b4857143cc57b2a8afa4be18c0f1f63
> [releng] Update Sirius version to 6.5.1 release

- releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Iac07b6f0848ad1416156ed555167b326aaa9030e
> [releng] Update to Kitalpha 5.1.0-IT4

- Jenkinsfile
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I95f710877542c84261225c5f619b0846fe79ba1f
> #2210 Fix target platform

- .gitignore
- releng/plugins/org.polarsys.capella.rcp.product/capella.product
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.massactions.ju/src/org/polarsys/capella/test/massactions/ju/testcases/view/shared/ColumnReorderTest.java
- tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout
Migrate TP to include:
- Kitalpha 6.0
- Nattable 2.0.1
- Nebula 2.3.0
Massaction test update based on Kitalpha's modifications done for https://github.com/eclipse/kitalpha/issues/677
> [releng] Migration 2021-06 - Kitalpha impacts

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/drop/DiagramDropAdapterAssistant.java
Fixes #2232 
Change-Id: Ica96d5903bce7a9287f67ef0f36b326402f94af1
> #2232 Extend D&D for other diagrams that the ones in org.polarsys.capella.core.sirius.analysis

- doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.03. Activity Browser.html
- doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.03. Activity Browser.mediawiki
Change-Id: I9e9c916b6003e2e1671e50c9e2cb7ddc22a8cef9
Signed-off-by: Cazoni Iulius-Alexandru <iulius.cazoni@thalesgroup.com>
> [doc] Update git doc

- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/toc.xml
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.migration.ju/model/migration.sysmodel/migration.sysmodel.aird.linux.layout
Change-Id: I61df34d31c0100b03632ea056d036402094b319a
> [releng] Update to Sirius S20211026-113903 and related Kitalpha

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
Resolve #2259 
Change-Id: Icac99288be170503a5530e2c8788f506e089a2c4
> #2259 Enable creation of ES/AS from AbstractCapabilities (OA level)

- core/plugins/org.polarsys.capella.core.transition.system.topdown/plugin.xml
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/IntramodelTransitionCommand.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/constants/Messages.java
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/constants/messages.properties
- core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/pa/PhysicalComponentRule.java
- core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/cs/ComponentRule.java
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
- tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.capella
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/CreateRule_Scenario_IS2IS_EPBS.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionsTestSuite.java
- tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_IS2IS_EPBS_04.java
Involvements
Change-Id: I550b905c3a3fac8b3d56c2559a239256e90af862
> #2263 Capability Transition to EPBS creates some inconsistent Involvements

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
- tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/DragDropTest.java
Change-Id: I89ffe1143da9e84594615d79fc106de8fea56aa7
> #2267 Fixed DnD a property from a Association to another

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/ODesignHelper.java
- tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/deletecheck/CheckDeletionDescriptionTest.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceCapabilityScenarioTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceCapabilityTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceScenarioTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceTableTestFramework.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/requirements/RequirementsTableTestCase.java
- tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/requirements/RequirementsTableTestFramework.java
Change-Id: I2e9747d69a51cef27470f53df21f179cd7ec4399
> #2270 Add missing Delete tools on Tables

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Iee5b37909d4ab7abbc8eda69c37e539fa90d648a
> [releng] Update Target platform for 5.2.0-IT3

- core/plugins/org.polarsys.capella.core.model.helpers/plugin.xml
- core/plugins/org.polarsys.capella.core.model.helpers/schema/moveHelper.exsd
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/IMoveHelper.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
Resolves: #2280 
Change-Id: I2970cbf61d20d5a4c92957043cdce351f90dec0f
> #2280 Added ExtensionPoint MoveHelper to allow customization of DnD/Copy-Paste

- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/SVGMigrationContribution.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/description/images/InFlowPort_left.svg
Add all new rotative SVG files to SVG migration contribution.
Add missing InFlowPort_left SVG image
> #2273 Update SVG migration contribution to add rotative SVGs

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentExt.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/ComponentExtTestCase.java
Change-Id: I0d58c60ffdd7d2c39dc2f3868e9145c9d2bf82f1
Signed-off-by: Cazoni Iulius-Alexandru <iulius.cazoni@thalesgroup.com>
> #2312 fixing the error that occurs when creating a new Interaction

- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/14_Other shortcut keys/14_Other shortcut keys.html
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/14_Other shortcut keys/14_Other shortcut keys.mediawiki
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.html
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.mediawiki
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/license.txt
Change-Id: I3ab49f8aa6a2899e0a599f341b1af719545c20c7
> #2321 Update tip and tricks for title blocks

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/CapellaApplication.java
>  #2334 Workspace in use message

- doc/plugins/org.polarsys.capella.developer.doc/html/Development Environment.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Development Environment.mediawiki
- doc/plugins/org.polarsys.capella.developer.doc/toc.xml
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
Point to developent environment setup wiki page.
Update setup steps to use a custom JRE/JDK.
>  #2349 Update documentation

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
> [releng] Update to Sirius 7.0.1-S20220314-093652

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
> [releng] Update to Kitalpha 6.0.0.S202203161338

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/AbstractDependenciesPkgExt.java
Change-Id: I3c3e391f242ca826416b2f3c05dc417716db2ef3
Signed-off-by: Cazoni Iulius-Alexandru <iulius.cazoni@thalesgroup.com>
> #2368 Improved performance when extracting dependencies

- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/sirius/diagram/AbstractModelElementRelatedRepresentationQuery.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserViewerComparator.java
Sort diagrams according to their name in SemanticBrowser.
>  #2383 Use correct diagram ordering in SemanticBrowser

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Id99c8d76d8d60ddf5eb01ff5a0fe331506c45322
Signed-off-by: Boubekeur Zendagui <boubekeur.zendagui@thalesgroup.com>
> Integration of Sirius 7.0.1rc2/2021-06

- releng/features/org.polarsys.capella.rcp/feature.xml
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Fixes #2388
Change-Id: I0a9258aeee950b902ef714f4a1e637aced0c7998
> #2388 Add SLF4J implementation into Capella product to avoid SLF4J warning

- core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/fields/BasicElementGroup.java
- core/plugins/org.polarsys.capella.core.data.information.datavalue.properties/src/org/polarsys/capella/core/data/information/datavalue/properties/fields/UnparsedExpressionGroup.java
- core/plugins/org.polarsys.capella.core.data.information.datavalue.properties/src/org/polarsys/capella/core/data/information/datavalue/properties/sections/OpaqueExpressionSection.java
- core/plugins/org.polarsys.capella.core.data.requirement.properties/src/org/polarsys/capella/core/data/requirement/properties/fields/RequirementGroup.java
- core/plugins/org.polarsys.capella.core.data.requirement.properties/src/org/polarsys/capella/core/data/requirement/properties/fields/RequirementsPkgGroup.java
- core/plugins/org.polarsys.capella.core.ui.properties.descriptions/src/org/polarsys/capella/core/ui/properties/descriptions/fields/ElementDescriptionGroup.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/fields/ConstraintReferenceField.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/fields/TextAreaValueGroup.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/fields/TextValueGroup.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/sections/DiagramRepresentationPropertySection.java
- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/wizards/EditCapellaCustomPropertyWizardPage.java
Resolves: #2389
Signed-off-by: Georgiana Ecobici
<georgiana-elena.ecobici@thalesgroup.com>
Change-Id: I3a8aecdf9214854792bdc7b95f20990ee40301ee
> #2389 Add widthHint to wrap long text

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I5740411a9ee1dc0a66815922c6349e320eb5ce4f
> [Releng] Integration of Sirius 7.0.1-S20220504-052320

- core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/wizards/EditCapellaCustomPropertyWizardPage.java
Resolves: #2389
Change-Id: I6a4736cb83949e34bce09c01d30d6f6081fede98
> #2389 Revert widthHint for some fields (description)

- core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
#2400 
Change-Id: I9e2fe2a8cf50b4029d96faf8406aa6e9c64fcced
> #2400 Fixed description tab

- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/category/CategoryImpl.java
- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/category/ICategory.java
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.mediawiki
Change-Id: I94b5f9fb62dac921d02af1498b7e5322499598e5
> #2376 Add API on ICategory to access to the corresponding IQuery

- releng/plugins/org.polarsys.capella.rcp.product/capella.product
Set Java dependency to JavaSE-11
Change-Id: I0000000000000000000000000000000000000000
Signed-off-by: Arnaud Dieumegard <arnaud.dieumegard@obeo.fr>
>  #2398 Harmonize all platform distribution packaging

- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/ToolHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/ConstraintRename.java
Change-Id: I7ecd104460b24b04efb5b831b8ed5a788b5b5a9f
> [tests] Fix ConstraintRename test

- core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
This reverts commit ef58fe03083b3ffd93e304955580d794dd41599e.
> Revert "#2396 Avoid the description tab to be refreshed twice"

- pom.xml
Change-Id: I47b7852b48e371c86e6e28c56537d798f95ceb26
> [releng] Update rcptt version

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- Amalgam 1.13.0-S20220524
- Diffmerge 0.14.0-S20220524
- Sirius 7.0.1-S20220519-115310
- Kitalpha 6.0.0.S202205250955
Change-Id: I4aa2d7f28832a5592490529a5682dbbb081ce714
Signed-off-by: Boubekeur Zendagui <boubekeur.zendagui@thalesgroup.com>
> [releng] Integrate Sirius 7.0.1-S20220519, Amalgam, Diffmerge n Kitalpha

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I76454d7fc62d10bd73d3b20352703cb8c6c3cf70
> [releng] Integrate Sirius 7.0.1rc3

- core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
Change-Id: I9b831bb39d95890226a8bdf5b69c8b1246abdc99
Signed-off-by: Cazoni Iulius-Alexandru <iulius.cazoni@thalesgroup.com>
> #2416 fixed removing x from the table

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
> [releng] Update Sirius 7.0.2rc3 and Diffmerge

- common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/merge/scope/TransitionSiriusImageHelper.java
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I3f82e24b3a9849dac4ad2d4eaf0958b831388fcb
> [releng] Update Diffmerge

- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
> [Doc] Update documentation about the embed of JDK instead of JRE in

- doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/toc.xml
> #2442-update_toc.xml

- doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
Change-Id: I8b13acddd244134140c04cece1557c44701e3118
> [doc] Regenerate developer.doc with build.xml

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ic65c91f29b8bd11aa5fabdc12139dd528ebda85f
> [releng] Update Sirius 7.0.4 and Kitalpha

- core/plugins/org.polarsys.capella.core.data.migration/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/Activator.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/participant/CapellaWorkspaceImageGMFBoundsMigrationParticipant.java
> #2465: Fix migration issue with collapsed ports

- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/participant/CapellaWorkspaceImageGMFBoundsMigrationParticipant.java
If we use a more recent version than the current version of Sirius in an migration participant, the model cannot be opened anymore
Bug: 2465
Change-Id: Ide38fdd72f4d28287a3ca1c27723f35097287f56
> #2465: Fix migration participant version

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/plugin.xml
> #1939 branch add exchange categories filter

- common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/activities/FinalizeTransitionActivity.java
Change-Id: Ib628d36dd4ba68fc55c17c99f729f735ac24f400
Signed-off-by: Irina Toma <irina_toma@rocketmail.com>
> Handle exception when clicking cancel on a subsystem transition

- core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/BasicCapellaDeleteCommand.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/Messages.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/messages.properties
Resolves: #2478
Change-Id: I1537dd00854499cfd8b60d449c70a9ec3e6bc53d
Signed-off-by: Irina Toma <irina_toma@rocketmail.com>
> #2478 Duplicate information in Delete dialog and Information view

- common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/impl/AbstractContentProvider.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/content/provider/SiriusSemanticBrowserContentProviderFactory.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/wrapper/CustomEObjectWrapper.java
- tests/plugins/org.polarsys.capella.test.semantic.ui.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.semantic.ui.ju/model/DiagramNavigationModel/DiagramNavigationModel.aird
- tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testcases/SemanticBrowserRepresentationHasSemanticQueriesTest.java
- tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testsuites/SemanticUITestSuite.java
Selecting a PP/OP/FC/Scenario Representation now also displays queries on their target element
Added cache in item provider in order not to compute queries multiple times
Change-Id: I6125506e61970826393466a9f62dd4ef0d86f109
> #2451 PP/OP/FC/Scenario Representation queries

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/AbstractNewRepresentationAction.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenRepresentationsAction.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/DescriptionImageDescriptorHelper.java
Change-Id: I32d06d89a9ed4a904d369e89ca9cc8219914596f
> #2483 Fixed missing icons in Diagram creation menu

- common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/TreeAndListViewer.java
Added Status bar width hint
Change-Id: I926cede8214968c9c28204dae9eb0ab3c239fb65
> #2482 Fixed Capella Deletion wizard size

- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quicfix/helpers/QuickFixNavigationHelper.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Delete.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Source.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Target.java
- core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.fa.validation/src/org/polarsys/capella/core/data/fa/validation/functionalExchange/FunctionalExchange_loopsOnSameFunction.java
- core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/fa/services/FunctionExt.java
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DFServices.java
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/completeness/ValidationRules.html
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/completeness/ValidationRules.mediawiki
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dcom/Rule_DCOM_23.java
Resolves #2490
Change-Id: Idc8d7cfcd3e62c2508b17348642ddf08d6fe3fe4
Signed-off-by: Irina Toma <irina_toma@rocketmail.com>
> [#2490] Functional Exchange looping on the same function

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/CreateComponentExchangeGroup.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/CreatePhysicalLink.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/XABDiagramsProject.java
Change-Id: I96609c39c9af40897f3fe4ce158ef21d212793d3
> #2485 Allow create several PL/CE between a couple of ports

- core/plugins/org.polarsys.capella.core.data.interaction.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.interaction.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.interaction.ui.quickfix/src/org/polarsys/capella/core/data/interaction/ui/quickfix/resolver/AddAllExchangeItemsToSequenceMessageResolver.java
- core/plugins/org.polarsys.capella.core.data.interaction.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/sequenceMessage/SequenceMessageInvokedOperationExchangeItems.java
- core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/fc2fs/FC2FSInitialization.java
- doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.mediawiki
- tests/plugins/org.polarsys.capella.test.projection.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.projection.ju/model/FunctionalChain/.project
- tests/plugins/org.polarsys.capella.test.projection.ju/model/FunctionalChain/FunctionalChain.afm
- tests/plugins/org.polarsys.capella.test.projection.ju/model/FunctionalChain/FunctionalChain.aird
- tests/plugins/org.polarsys.capella.test.projection.ju/model/FunctionalChain/FunctionalChain.capella
- tests/plugins/org.polarsys.capella.test.projection.ju/src/org/polarsys/capella/test/projection/ju/FC2FSTest.java
- tests/plugins/org.polarsys.capella.test.projection.ju/src/org/polarsys/capella/test/projection/ju/ProjectionTestSuite.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_ds/Rule_DWF_DS_12.java
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_ds/Rule_DWF_DS_25.java
SequenceMessages created during the FC2FS projection shall include the assignment of the ExchangeItem on the SequenceMessages allocated on the FunctionalChainInvolvementLinks.
It applies on transition from FunctionalChains and OperationalProcesses.
> Assign ExchangeItems on FunctionalChain to Scenario initialization

- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.properties
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/plugin.xml
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_23_Resolver_Functional_Exchange.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_23_Resolver_Interaction.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Delete.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Source.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Source_Function.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Source_Operational_Activity.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Target.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Target_Function.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_20_Resolver_Target_Operational_Activity.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_PortResolver_Source.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_PortResolver_Target.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Abstract_Function.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Looping_Activity.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DCOM_23_Resolver_Looping_Function.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/FunctionalExchangeResolver.java
- core/plugins/org.polarsys.capella.core.data.fa.validation/plugin.xml
- core/plugins/org.polarsys.capella.core.data.fa.validation/src/org/polarsys/capella/core/data/fa/validation/functionalExchange/FunctionalExchange_loopsOnSameFunction.java
Change-Id: I9d1f7546ecd6e55b2384c247ef7e696d8fcbf8da
> [9968] Added QF for DCOM_23 and DCOM_20

- core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
Change-Id: Ie94e7b9e3e784a11eba67173159167e40e11bbb8
> #2461 Restore Diagram Preference page name that was missing

- core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/MigrationConstants.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/ImageDependenciesMigrationContributor.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/Messages.java
- core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/messages.properties
- releng/plugins/org.polarsys.capella.rcp.product/pom.xml
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.layout.ju/src/org/polarsys/capella/test/diagram/layout/ju/testcases/CopyPasteLayout.java
- tests/plugins/org.polarsys.capella.test.framework/META-INF/MANIFEST.MF
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/CapellaTestFrameworkPlugin.java
- tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testcases/basic/ImagePathInRichTextAttributeMigrationTest.java
> #2524 Add a migration contributor to update the image project

- common/plugins/org.polarsys.capella.common.flexibility.wizards/src/org/polarsys/capella/common/flexibility/wizards/ui/tabbed/FixedTabDescriptorProvider.java
Property sections can now be filtered by activities, bind it to an activity that matches 'sectionId'.
Tabs are hidden by default if there is no sections in it
Automatic refresh when activities change is not performed. The user has to re-select the element to make tab changes visible in the view.
> #2554 Filter property sections via activity bindings

- core/plugins/org.polarsys.capella.core.transition.common.ui/src/org/polarsys/capella/core/transition/common/ui/handlers/merge/DiffCategoryProxy.java
Change-Id: I83b6fd0c3ca47acab4a02ea8eafd3ad48590c8fa
> #2578 Fixed blocker sonar issue

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: I4e72f7866eceb130d58262b70e5f72dd2b34fc0e
> [releng] Update to Sirius 7.1.0-S20230210-122000

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidCECategoryMenuTargetTester.java
Change-Id: I2258649114d03039eedaa793164bdec4195e3e25
> #2567 Dummy fixes on Capella right click menus

- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreateFunctionalChainActionHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreatePhysicalPathActionHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/AbstractValidCategoryMenuTargetTester.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidFCMenuTargetTester.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidPPMenuTargetTester.java
- Create Functional Chain on Functional Exchange labels
- Create Physical Path on Physical Links
- Create / Update Category on Functional Exchange, Component Exchange and Physical Links
> #2587 fix regressions :

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/policies/OpenRelatedDiagramEditPolicy.java
double-click navigation on FC/PP/OP did not work in Team context - fixed it
Change-Id: I4be3b4a450be70128436e0825fe64d616be4d88f
> #2600 Fixed double-click navigation not working on Team

- tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockFilterTest.java
- tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockMappingTest.java
- tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockToolTest.java
Junit tests on TitleBlock did not work in Team context List of available viewpoint was not limited to Capella
Change-Id: I32faf368af7747f94f0807229850c588346da0f3
> #2609 Fixed JUnit on TitleBlock

- tests/plugins/org.polarsys.capella.test.rcptt/CopyPasteCut/CopyPasteWithZoom.test
- tests/plugins/org.polarsys.capella.test.rcptt/Library/AccessPolicyRecRpl.test
- tests/plugins/org.polarsys.capella.test.rcptt/MassActions/SendTo/MESendToFromProjectExplorer.test
- tests/plugins/org.polarsys.capella.test.rcptt/MassActions/SendTo/MVSendToFromProjectExplorer.test
- tests/plugins/org.polarsys.capella.test.rcptt/Menu/NavigationMenu.test
- tests/plugins/org.polarsys.capella.test.rcptt/ProjectExplorer/LocatedElementIsFilteredInCapellaExplorer_GoTo.test
- tests/plugins/org.polarsys.capella.test.rcptt/ProjectExplorer/QuickFiltersMenuTest.test
- tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/RecRpl.test
- tests/plugins/org.polarsys.capella.test.rcptt/Sequence/FunctionalExchangeWhenAllocationWithoutTarget.test
- tests/plugins/org.polarsys.capella.test.rcptt/Sequence/PrePostConditionDeletionImpactAnalysis.test
- tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceManagerWizard.test
- tests/plugins/org.polarsys.capella.test.rcptt/ValidationProfile/ProjectConfiguration.test
- tests/plugins/org.polarsys.capella.test.rcptt/contexts/default/CapellaEnableHiddenCapabilities.ctx
- tests/plugins/org.polarsys.capella.test.rcptt/contexts/default/CapellaExplorerFilters.ctx
- tests/plugins/org.polarsys.capella.test.rcptt/rcptt.properties
Change-Id: I12a48d9d9bc3c87a735697d9870aaa6d2f6abf8b
> [Test] Migrate RCPTT tests

- core/plugins/org.polarsys.capella.core.model.helpers/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/WriteCapellaElementDescriptionSAXParser.java
- core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/InvalidNameHandler.java
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.aird
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.capella
- tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_22.java
Also Fixed error detection on incorrect label
Change-Id: If331845483a2e30de67015828fa7aa64c0c2dd27
> #2625 Label of linked elements in description is now properly encoded

- core/plugins/org.polarsys.capella.core.explorer.activity.ui/plugin.xml
- core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/pa/PerformAutomatedCapabilitiesTransitionAdapter.java
Activity action now properly transition from LA instead of SA
Change-Id: I08f33a58901672e23dfb6eccc33975779b27f953
> #2642 fixed Activity Transition LA > PA of Capabilities

- releng/plugins/org.polarsys.capella.rcp.product/capella.product
Change-Id: Id2c81ab2a4fffa88c1efcc41a7f37309d251a108
> #2647 Use Edge as default browser on windows

- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/CapellaElementReferencingScenario.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/AbstractFunction_ReferencingScenarios.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
This query now also displayed scenarii in which the function is invoked as source or target of a sequence message
Change-Id: I06419a373c5789f08da6e84a4db8c3fd53d0e459
> #2650 Improve SB "Scenarios" query on Abstract Function

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
The official release doesn't require many stuff anymore
> [releng] Update Mylyn to 3.26 official

- core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
- tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/accelerators/PhysicalLinkAcceleratorTest.java
- tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/MiscModel.java
bug1: creation of physical link on a PC behaviour is forbidden
solution1: verify if target component is a node
bug2: PL cannot be created on target of type actor if source has container parent and target has not
solution: if target container is not a component use target contained
> Fix Accelerators issues related to Physical Links generated on invalid targets

- core/plugins/org.polarsys.capella.core.data.business.queries/src/org/polarsys/capella/core/business/queries/queries/cs/GetAvailable_PhysicalLink_AllocatedComponentExchanges.java
- core/plugins/org.polarsys.capella.core.data.business.queries/src/org/polarsys/capella/core/business/queries/queries/cs/GetAvailable_PhysicalPort_AllocatedComponentPorts.java
- tests/plugins/org.polarsys.capella.test.business.queries.ju/testSuite/sysmodel/cs/org.polarsys.capella.core.business.queries.cs.PhysicalPort_AllocatedComponentPorts.testSuite
similar logic to CE for physical links
refactor GetAvailable_PhysicalPort_AllocatedComponentPorts and GetAvailable_PhysicalLink_AllocatedComponentExchanges
> #2709 propose similar allocated ports for physical port

- core/plugins/org.polarsys.capella.core.model.obfuscator/src/org/polarsys/capella/core/model/obfuscator/actions/ObfuscateSessionAction.java
Aird content is specifically managed by obfuscateRepresentation() method
> #2693 Do not obfuscate aird files listed as semantic resources

- releng/plugins/org.polarsys.capella.rcp.product/capella.product
- tests/plugins/org.polarsys.capella.test.suite.inui.ju/launch_config/RunInUITestSuite.launch
- tests/plugins/org.polarsys.capella.test.suite.local.ju/launch_config/LocalTestSuite.launch
- tests/plugins/org.polarsys.capella.test.suite.notinui.ju/launch_config/RunInNotUITestSuite.launch
Change-Id: If3cf937d26682a0246c05db66fd8c395c2cb71d2
> Use G1GC and StringDeduplication in Capella

- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/commands/AddTrace.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/extension/ITraceExtension.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/extension/TraceExtensionManager.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/messages/TraceNameHelper.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/messages/TraceUtil.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/SelectTraceType.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/ViewEditPage.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/providers/ElementLabelProvider.java
- core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/providers/TypeElementFilter.java
Contribution is now only enabled when the viewpoint is activated on the current model
Change-Id: I62a14fa734a24aa445cb22e027ef73e03d8f5aac
> #2708 Trace contributions enabled on vp activation

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
- core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/SelectRelatedFCElementsCommandHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/SelectRelatedPPElementsCommandHandler.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/SelectionHelper.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/AbstractValidSelectionMenuTarget.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidFCSelectionMenuTargetTester.java
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidPPSelectionMenuTargetTester.java
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.html
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.mediawiki
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/CommonDiagram.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/In-Flight Entertainment System/In-Flight Entertainment System.capella
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/common/SelectToolsTest.java
selects all ports, categories and links
Change-Id: Ic5348bdb7561ca648555e280d901d43eb8f410de
> #2749 New action to select all related elements of a PP or FC

- core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/messages.properties
Change-Id: I9cf74fbe6633e7f03d533fe988fd109bbac7251b
> #2737 Fix issue with library dialog warning labels

- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/AbstractSelectOneResolver.java
- core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DWF_DC_27_Resolver.java
Fix class cast exception that prevented DWF_DC_12 to be resolved
Change-Id: I86e8955fb2b0488dcf9a1b3dee24cfdab99f6069
> #2743 Fix dialog label in DWF_DC_27 resolver

- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
- doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
Change-Id: Idc0ada73a041bce75c4de5d044398f12d110d0a6
> #2761 Add workaround for leading / in command line support documentation

- core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
- core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidOPSelectionMenuTargetTester.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/common/SelectToolsTest.java
Changed name on OperationalProcess
Added Junit
Change-Id: I43277a3808645134abf6aa1b02a49e5b74504727
> #2749 Select Related Operational Process Elements

- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropFunction.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DragAndDropPhysicalComponent.java
- tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/ShowHidePortAllocations.java
Removal of unused code duplication
The 3  modified classes each extends XABDiagramsProject, which implements the removed method with the exact same result.
> [cleanup] test classes cleanup

- core/plugins/org.polarsys.capella.core.ui.semantic.browser/META-INF/MANIFEST.MF
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/label/provider/SemanticBrowserDecoratingLabelProvider.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/label/provider/SemanticBrowserLabelProvider.java
- core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/label/provider/SemanticBrowserLabelProviderFactoryImpl.java
same decorators as the ones from label decorations preference
Change-Id: Idbb08712dfb1f825335e5f6e0572a5456fbfd46d
> #2778 Displays decorators in SemanticBrowser

- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/ComparisonHelper.java
- tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/diffModel/StructureDiffComparison.java
Too much code was removed when requirement capabilities were removed Restore it
Also fix an issue where default id would never be displayed as scope was always null
Change-Id: I7b6eb92cfdb381b11340037dbf5ac1c887294b1c
> #2687 Fix issue with StructureDiffComparison

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/CapellaWorkbenchWindowAdvisor.java
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/IWelcomeView.java
- doc/plugins/org.polarsys.capella.core.ui.intro/META-INF/MANIFEST.MF
- doc/plugins/org.polarsys.capella.core.ui.intro/src/org/polarsys/capella/core/ui/intro/views/WelcomeView.java
Change-Id: Ie228d2257fe5f8ea5c5eabf22af9b96401b6545a
> #2662 Avoid ClassCastException on WelcomeView

- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/src/org/polarsys/capella/core/platform/sirius/ui/app/CapellaWorkbenchWindowAdvisor.java
Change-Id: I12870e75ed13d825ce3121643e5b8a3d0923ebfd
> #2799 Fixed blank welcome view on first opening

- Jenkinsfile
- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Maven process doesn't need that much memory, as its more sub processes that will require it. (eclipse director that will create product in that current case)
> [releng] Fix memory issue on build

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
use LinkedHashSet to remove duplicates
Change-Id: I1244524ea0bb07057f4b09e5d15d1e48827b4af7
> #2789 Fix semanticElements on FE/PL

- core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/cs/services/PhysicalLinkExt.java
Change HashSet to LinkedHashSet
Change-Id: I1afd6292a6dc3fb5a520e47398fff484041153a6
> #2832 Fix issue with physical links order returned by PhysicalLinkExt

- CONTRIBUTING.md
- NOTICE.md
- README.md
- core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/about.properties
- doc/plugins/org.polarsys.capella.core.ui.intro/plugin.xml
- doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.mediawiki
- doc/plugins/org.polarsys.capella.developer.doc/html/Development Environment.mediawiki
- doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
- doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/Whatsnew.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/Whatsnew.mediawiki
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.html
- doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.mediawiki
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
- doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
- pom.xml
- releng/plugins/org.polarsys.capella.rcp/about.properties
> #2836 Changed links to eclipse-capella

- doc/plugins/org.polarsys.capella.doc/html/Release note/API_6.x_to_7.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/API_6.x_to_7.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/html/Release note/M2_6.x_to_7.x.html
- doc/plugins/org.polarsys.capella.doc/html/Release note/M2_6.x_to_7.x.mediawiki
- doc/plugins/org.polarsys.capella.doc/toc.xml
- doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/3.5. How to migrate Capella projects.html
- doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/3.5. How to migrate Capella projects.mediawiki
> #2844 Updated Release notes and metamodel changes

- common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/subcommands/handlers/SubCommandHandler.java
Fixes errors on startup
Change-Id: I051ef78258d217897f2c31ccbee8ef2095c620d4
> #2852 Add guard on null selection

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
Change-Id: I1245ddf67e0508aeb7c4bee675ed83f562df0105
> #2853 Add cache on FE/PL edge semanticElements computation

- core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/StateExt.java
- core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/AbstractStateParentActiveElements.java
- tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
Change-Id: I25f3b0e7bdc0a33f147a3b439aa2a3638f0b0b04
> #2873 fix state query for activated elements

- core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
- tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
- tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/PieIconTest.java
This PR takes over the commit of PR #2895 by fixing tests.
> #2894 Avoid potential deadlocks in refresh

- releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Change-Id: Ia263c098847b8c8708d08ec063eb0b6c88327f76
> [releng] Switch to Sirius 7.4.5-S20241126-110306
